local get_ordinal = require('command_pal.ordinal').get_ordinal
local default_handler = require('command_pal.handler').default_handler
local set_cmd = require('command_pal.utils').set_cmdline

---@class provider.Builtin : provider.Base
---@field builtin builtin.BuiltinT
local M = {}

---@class builtin.Value
---@field name string
---@field desc string
---@field bang? boolean
---@field command? boolean
---@field ordinal? string

---@class builtin.BuiltinT
---@field [string] builtin.Value

-- TODO: use script for this
-- '<,'>s/|:\(.*\)|\s*:\S*\s*\(.*\)/[":\1"]={name=[[\1]], desc = [[\2]], command = true},
M.builtin = {
  [':range'] = { name = [[range]], desc = [[go to last line in {range}]] },
  [':!'] = { name = [[!]], desc = [[filter lines or execute an external command]] },
  [':!!'] = { name = [[!!]], desc = [[repeat last ":!" command]] },
  [':#'] = { name = [[#]], desc = [[same as ":number"]] },
  [':&'] = { name = [[&]], desc = [[repeat last ":substitute"]] },
  [':star'] = { name = [[star]], desc = [[use the last Visual area, like ":'<,'>"]] },
  [':<'] = { name = [[<]], desc = [[shift lines one 'shiftwidth' left]] },
  [':='] = { name = [[=]], desc = [[print the last line number]] },
  [':>'] = { name = [[>]], desc = [[shift lines one 'shiftwidth' right]] },
  [':@'] = { name = [[@]], desc = [[execute contents of a register]] },
  [':@@'] = { name = [[@@]], desc = [[repeat the previous ":@"]] },
  [':2match'] = { name = [[2match]], desc = [[define a second match to highlight]] },
  [':3match'] = { name = [[3match]], desc = [[define a third match to highlight]] },
  [':Next'] = { name = [[Next]], desc = [[go to previous file in the argument list]] },
  [':append'] = { name = [[append]], desc = [[append text]] },
  [':abbreviate'] = { name = [[abbreviate]], desc = [[enter abbreviation]] },
  [':abclear'] = { name = [[abclear]], desc = [[remove all abbreviations]] },
  [':aboveleft'] = { name = [[aboveleft]], desc = [[make split window appear left or above]] },
  [':all'] = { name = [[all]], desc = [[open a window for each file in the argument list]] },
  [':amenu'] = { name = [[amenu]], desc = [[enter new menu item for all modes]] },
  [':anoremenu'] = {
    name = [[anoremenu]],
    desc = [[enter a new menu for all modes that will not be remapped]],
    command = true,
  },
  [':args'] = { name = [[args]], desc = [[print the argument list]] },
  [':argadd'] = { name = [[argadd]], desc = [[add items to the argument list]] },
  [':argdedupe'] = { name = [[argdedupe]], desc = [[remove duplicates from the argument list]] },
  [':argdelete'] = { name = [[argdelete]], desc = [[delete items from the argument list]] },
  [':argedit'] = { name = [[argedit]], desc = [[add item to the argument list and edit it]] },
  [':argdo'] = { name = [[argdo]], desc = [[do a command on all items in the argument list]] },
  [':argglobal'] = { name = [[argglobal]], desc = [[define the global argument list]] },
  [':arglocal'] = { name = [[arglocal]], desc = [[define a local argument list]] },
  [':argument'] = { name = [[argument]], desc = [[go to specific file in the argument list]] },
  [':ascii'] = { name = [[ascii]], desc = [[print ascii value of character under the cursor]] },
  [':autocmd'] = { name = [[autocmd]], desc = [[enter or show autocommands]] },
  [':augroup'] = { name = [[augroup]], desc = [[select the autocommand group to use]] },
  [':aunmenu'] = { name = [[aunmenu]], desc = [[remove menu for all modes]] },
  [':buffer'] = { name = [[buffer]], desc = [[go to specific buffer in the buffer list]] },
  [':bNext'] = { name = [[bNext]], desc = [[go to previous buffer in the buffer list]] },
  [':ball'] = { name = [[ball]], desc = [[open a window for each buffer in the buffer list]] },
  [':badd'] = { name = [[badd]], desc = [[add buffer to the buffer list]] },
  [':balt'] = { name = [[balt]], desc = [[like ":badd" but also set the alternate file]] },
  [':bdelete'] = { name = [[bdelete]], desc = [[remove a buffer from the buffer list]] },
  [':belowright'] = { name = [[belowright]], desc = [[make split window appear right or below]] },
  [':bfirst'] = { name = [[bfirst]], desc = [[go to first buffer in the buffer list]] },
  [':blast'] = { name = [[blast]], desc = [[go to last buffer in the buffer list]] },
  [':bmodified'] = {
    name = [[bmodified]],
    desc = [[go to next buffer in the buffer list that has been modified]],
    command = true,
  },
  [':bnext'] = { name = [[bnext]], desc = [[go to next buffer in the buffer list]] },
  [':botright'] = { name = [[botright]], desc = [[make split window appear at bottom or far right]] },
  [':bprevious'] = { name = [[bprevious]], desc = [[go to previous buffer in the buffer list]] },
  [':brewind'] = { name = [[brewind]], desc = [[go to first buffer in the buffer list]] },
  [':break'] = { name = [[break]], desc = [[break out of while loop]] },
  [':breakadd'] = { name = [[breakadd]], desc = [[add a debugger breakpoint]] },
  [':breakdel'] = { name = [[breakdel]], desc = [[delete a debugger breakpoint]] },
  [':breaklist'] = { name = [[breaklist]], desc = [[list debugger breakpoints]] },
  [':browse'] = { name = [[browse]], desc = [[use file selection dialog]] },
  [':bufdo'] = { name = [[bufdo]], desc = [[execute command in each listed buffer]] },
  [':buffers'] = { name = [[buffers]], desc = [[list all files in the buffer list]] },
  [':bunload'] = { name = [[bunload]], desc = [[unload a specific buffer]] },
  [':bwipeout'] = { name = [[bwipeout]], desc = [[really delete a buffer]] },
  [':change'] = { name = [[change]], desc = [[replace a line or series of lines]] },
  [':cNext'] = { name = [[cNext]], desc = [[go to previous error]] },
  [':cNfile'] = { name = [[cNfile]], desc = [[go to last error in previous file]] },
  [':cabbrev'] = { name = [[cabbrev]], desc = [[like ":abbreviate" but for Command-line mode]] },
  [':cabclear'] = { name = [[cabclear]], desc = [[clear all abbreviations for Command-line mode]] },
  [':cabove'] = { name = [[cabove]], desc = [[go to error above current line]] },
  [':caddbuffer'] = { name = [[caddbuffer]], desc = [[add errors from buffer]] },
  [':caddexpr'] = { name = [[caddexpr]], desc = [[add errors from expr]] },
  [':caddfile'] = { name = [[caddfile]], desc = [[add error message to current quickfix list]] },
  [':cafter'] = { name = [[cafter]], desc = [[go to error after current cursor]] },
  [':call'] = { name = [[call]], desc = [[call a function]] },
  [':catch'] = { name = [[catch]], desc = [[part of a :try command]] },
  [':cbefore'] = { name = [[cbefore]], desc = [[go to error before current cursor]] },
  [':cbelow'] = { name = [[cbelow]], desc = [[go to error below current line]] },
  [':cbottom'] = { name = [[cbottom]], desc = [[scroll to the bottom of the quickfix window]] },
  [':cbuffer'] = { name = [[cbuffer]], desc = [[parse error messages and jump to first error]] },
  [':cc'] = { name = [[cc]], desc = [[go to specific error]] },
  [':cclose'] = { name = [[cclose]], desc = [[close quickfix window]] },
  [':cd'] = { name = [[cd]], desc = [[change directory]] },
  [':cdo'] = { name = [[cdo]], desc = [[execute command in each valid error list entry]] },
  [':cfdo'] = { name = [[cfdo]], desc = [[execute command in each file in error list]] },
  [':center'] = { name = [[center]], desc = [[format lines at the center]] },
  [':cexpr'] = { name = [[cexpr]], desc = [[read errors from expr and jump to first]] },
  [':cfile'] = { name = [[cfile]], desc = [[read file with error messages and jump to first]] },
  [':cfirst'] = { name = [[cfirst]], desc = [[go to the specified error, default first one]] },
  [':cgetbuffer'] = { name = [[cgetbuffer]], desc = [[get errors from buffer]] },
  [':cgetexpr'] = { name = [[cgetexpr]], desc = [[get errors from expr]] },
  [':cgetfile'] = { name = [[cgetfile]], desc = [[read file with error messages]] },
  [':changes'] = { name = [[changes]], desc = [[print the change list]] },
  [':chdir'] = { name = [[chdir]], desc = [[change directory]] },
  [':checkhealth'] = { name = [[checkhealth]], desc = [[run healthchecks]] },
  [':checkpath'] = { name = [[checkpath]], desc = [[list included files]] },
  [':checktime'] = { name = [[checktime]], desc = [[check timestamp of loaded buffers]] },
  [':chistory'] = { name = [[chistory]], desc = [[list the error lists]] },
  [':clast'] = { name = [[clast]], desc = [[go to the specified error, default last one]] },
  [':clearjumps'] = { name = [[clearjumps]], desc = [[clear the jump list]] },
  [':clist'] = { name = [[clist]], desc = [[list all errors]] },
  [':close'] = { name = [[close]], desc = [[close current window]] },
  [':cmap'] = { name = [[cmap]], desc = [[like ":map" but for Command-line mode]] },
  [':cmapclear'] = { name = [[cmapclear]], desc = [[clear all mappings for Command-line mode]] },
  [':cmenu'] = { name = [[cmenu]], desc = [[add menu for Command-line mode]] },
  [':cnext'] = { name = [[cnext]], desc = [[go to next error]] },
  [':cnewer'] = { name = [[cnewer]], desc = [[go to newer error list]] },
  [':cnfile'] = { name = [[cnfile]], desc = [[go to first error in next file]] },
  [':cnoremap'] = { name = [[cnoremap]], desc = [[like ":noremap" but for Command-line mode]] },
  [':cnoreabbrev'] = { name = [[cnoreabbrev]], desc = [[like ":noreabbrev" but for Command-line mode]] },
  [':cnoremenu'] = { name = [[cnoremenu]], desc = [[like ":noremenu" but for Command-line mode]] },
  [':copy'] = { name = [[copy]], desc = [[copy lines]] },
  [':colder'] = { name = [[colder]], desc = [[go to older error list]] },
  [':colorscheme'] = { name = [[colorscheme]], desc = [[load a specific color scheme]] },
  [':command'] = { name = [[command]], desc = [[create user-defined command]] },
  [':comclear'] = { name = [[comclear]], desc = [[clear all user-defined commands]] },
  [':compiler'] = { name = [[compiler]], desc = [[do settings for a specific compiler]] },
  [':continue'] = { name = [[continue]], desc = [[go back to :while]] },
  [':confirm'] = { name = [[confirm]], desc = [[prompt user when confirmation required]] },
  [':const'] = { name = [[const]], desc = [[create a variable as a constant]] },
  [':copen'] = { name = [[copen]], desc = [[open quickfix window]] },
  [':cprevious'] = { name = [[cprevious]], desc = [[go to previous error]] },
  [':cpfile'] = { name = [[cpfile]], desc = [[go to last error in previous file]] },
  [':cquit'] = { name = [[cquit]], desc = [[quit Vim with an error code]] },
  [':crewind'] = { name = [[crewind]], desc = [[go to the specified error, default first one]] },
  [':cunmap'] = { name = [[cunmap]], desc = [[like ":unmap" but for Command-line mode]] },
  [':cunabbrev'] = { name = [[cunabbrev]], desc = [[like ":unabbrev" but for Command-line mode]] },
  [':cunmenu'] = { name = [[cunmenu]], desc = [[remove menu for Command-line mode]] },
  [':cwindow'] = { name = [[cwindow]], desc = [[open or close quickfix window]] },
  [':delete'] = { name = [[delete]], desc = [[delete lines]] },
  [':debug'] = { name = [[debug]], desc = [[run a command in debugging mode]] },
  [':debuggreedy'] = { name = [[debuggreedy]], desc = [[read debug mode commands from normal input]] },
  [':delcommand'] = { name = [[delcommand]], desc = [[delete user-defined command]] },
  [':delfunction'] = { name = [[delfunction]], desc = [[delete a user function]] },
  [':delmarks'] = { name = [[delmarks]], desc = [[delete marks]] },
  [':diffupdate'] = { name = [[diffupdate]], desc = [[update 'diff' buffers]] },
  [':diffget'] = { name = [[diffget]], desc = [[remove differences in current buffer]] },
  [':diffoff'] = { name = [[diffoff]], desc = [[switch off diff mode]] },
  [':diffpatch'] = { name = [[diffpatch]], desc = [[apply a patch and show differences]] },
  [':diffput'] = { name = [[diffput]], desc = [[remove differences in other buffer]] },
  [':diffsplit'] = { name = [[diffsplit]], desc = [[show differences with another file]] },
  [':diffthis'] = { name = [[diffthis]], desc = [[make current window a diff window]] },
  [':digraphs'] = { name = [[digraphs]], desc = [[show or enter digraphs]] },
  [':display'] = { name = [[display]], desc = [[display registers]] },
  [':djump'] = { name = [[djump]], desc = [[jump to #define]] },
  -- [':dl|		:dl		short for '] = { name = [[dl|		:dl		short for ]], desc = [[with the 'l' flag]] },
  [':dlist'] = { name = [[dlist]], desc = [[list #defines]] },
  [':doautocmd'] = { name = [[doautocmd]], desc = [[apply autocommands to current buffer]] },
  [':doautoall'] = { name = [[doautoall]], desc = [[apply autocommands for all loaded buffers]] },
  -- [':dp|		:d[elete]p	short for '] = {
  --   name = [[dp|		:d[elete]p	short for ]],
  --   desc = [[with the 'p' flag]],
  --   command = true,
  -- },
  [':drop'] = { name = [[drop]], desc = [[jump to window editing file or edit file in current window]] },
  [':dsearch'] = { name = [[dsearch]], desc = [[list one #define]] },
  [':dsplit'] = { name = [[dsplit]], desc = [[split window and jump to #define]] },
  [':edit'] = { name = [[edit]], desc = [[edit a file]] },
  [':earlier'] = { name = [[earlier]], desc = [[go to older change, undo]] },
  [':echo'] = { name = [[echo]], desc = [[echoes the result of expressions]] },
  [':echoerr'] = { name = [[echoerr]], desc = [[like :echo, show like an error and use history]] },
  [':echohl'] = { name = [[echohl]], desc = [[set highlighting for echo commands]] },
  [':echomsg'] = { name = [[echomsg]], desc = [[same as :echo, put message in history]] },
  [':echon'] = { name = [[echon]], desc = [[same as :echo, but without <EOL>]] },
  [':else'] = { name = [[else]], desc = [[part of an :if command]] },
  [':elseif'] = { name = [[elseif]], desc = [[part of an :if command]] },
  [':emenu'] = { name = [[emenu]], desc = [[execute a menu by name]] },
  [':endif'] = { name = [[endif]], desc = [[end previous :if]] },
  [':endfor'] = { name = [[endfor]], desc = [[end previous :for]] },
  [':endfunction'] = {
    name = [[endfunction]],
    desc = [[end of a user function started with :function]],
    command = true,
  },
  [':endtry'] = { name = [[endtry]], desc = [[end previous :try]] },
  [':endwhile'] = { name = [[endwhile]], desc = [[end previous :while]] },
  [':enew'] = { name = [[enew]], desc = [[edit a new, unnamed buffer]] },
  [':eval'] = { name = [[eval]], desc = [[evaluate an expression and discard the result]] },
  [':ex'] = { name = [[ex]], desc = [[same as ":edit"]] },
  [':execute'] = { name = [[execute]], desc = [[execute result of expressions]] },
  [':exit'] = { name = [[exit]], desc = [[same as ":xit"]] },
  [':exusage'] = { name = [[exusage]], desc = [[overview of Ex commands]] },
  [':fclose'] = { name = [[fclose]], desc = [[close floating window]] },
  [':file'] = { name = [[file]], desc = [[show or set the current file name]] },
  [':files'] = { name = [[files]], desc = [[list all files in the buffer list]] },
  [':filetype'] = { name = [[filetype]], desc = [[switch file type detection on/off]] },
  [':filter'] = { name = [[filter]], desc = [[filter output of following command]] },
  [':find'] = { name = [[find]], desc = [[find file in 'path' and edit it]] },
  [':finally'] = { name = [[finally]], desc = [[part of a :try command]] },
  [':finish'] = { name = [[finish]], desc = [[quit sourcing a Vim script]] },
  [':first'] = { name = [[first]], desc = [[go to the first file in the argument list]] },
  [':fold'] = { name = [[fold]], desc = [[create a fold]] },
  [':foldclose'] = { name = [[foldclose]], desc = [[close folds]] },
  [':folddoopen'] = { name = [[folddoopen]], desc = [[execute command on lines not in a closed fold]] },
  [':folddoclosed'] = { name = [[folddoclosed]], desc = [[execute command on lines in a closed fold]] },
  [':foldopen'] = { name = [[foldopen]], desc = [[open folds]] },
  [':for'] = { name = [[for]], desc = [[for loop]] },
  [':function'] = { name = [[function]], desc = [[define a user function]] },
  [':global'] = { name = [[global]], desc = [[execute commands for matching lines]] },
  [':goto'] = { name = [[goto]], desc = [[go to byte in the buffer]] },
  [':grep'] = { name = [[grep]], desc = [[run 'grepprg' and jump to first match]] },
  [':grepadd'] = { name = [[grepadd]], desc = [[like :grep, but append to current list]] },
  [':gui'] = { name = [[gui]], desc = [[start the GUI]] },
  [':gvim'] = { name = [[gvim]], desc = [[start the GUI]] },
  [':help'] = { name = [[help]], desc = [[open a help window]] },
  [':helpclose'] = { name = [[helpclose]], desc = [[close one help window]] },
  [':helpgrep'] = { name = [[helpgrep]], desc = [[like ":grep" but searches help files]] },
  [':helptags'] = { name = [[helptags]], desc = [[generate help tags for a directory]] },
  [':highlight'] = { name = [[highlight]], desc = [[specify highlighting methods]] },
  [':hide'] = { name = [[hide]], desc = [[hide current buffer for a command]] },
  [':history'] = { name = [[history]], desc = [[print a history list]] },
  [':horizontal'] = { name = [[horizontal]], desc = [[following window command work horizontally]] },
  [':insert'] = { name = [[insert]], desc = [[insert text]] },
  [':iabbrev'] = { name = [[iabbrev]], desc = [[like ":abbrev" but for Insert mode]] },
  [':iabclear'] = { name = [[iabclear]], desc = [[like ":abclear" but for Insert mode]] },
  [':if'] = { name = [[if]], desc = [[execute commands when condition met]] },
  [':ijump'] = { name = [[ijump]], desc = [[jump to definition of identifier]] },
  [':ilist'] = { name = [[ilist]], desc = [[list lines where identifier matches]] },
  [':imap'] = { name = [[imap]], desc = [[like ":map" but for Insert mode]] },
  [':imapclear'] = { name = [[imapclear]], desc = [[like ":mapclear" but for Insert mode]] },
  [':imenu'] = { name = [[imenu]], desc = [[add menu for Insert mode]] },
  [':inoremap'] = { name = [[inoremap]], desc = [[like ":noremap" but for Insert mode]] },
  [':inoreabbrev'] = { name = [[inoreabbrev]], desc = [[like ":noreabbrev" but for Insert mode]] },
  [':inoremenu'] = { name = [[inoremenu]], desc = [[like ":noremenu" but for Insert mode]] },
  [':intro'] = { name = [[intro]], desc = [[print the introductory message]] },
  [':isearch'] = { name = [[isearch]], desc = [[list one line where identifier matches]] },
  [':isplit'] = { name = [[isplit]], desc = [[split window and jump to definition of identifier]] },
  [':iunmap'] = { name = [[iunmap]], desc = [[like ":unmap" but for Insert mode]] },
  [':iunabbrev'] = { name = [[iunabbrev]], desc = [[like ":unabbrev" but for Insert mode]] },
  [':iunmenu'] = { name = [[iunmenu]], desc = [[remove menu for Insert mode]] },
  [':join'] = { name = [[join]], desc = [[join lines]] },
  [':jumps'] = { name = [[jumps]], desc = [[print the jump list]] },
  [':k'] = { name = [[k]], desc = [[set a mark]] },
  [':keepalt'] = { name = [[keepalt]], desc = [[following command keeps the alternate file]] },
  [':keepmarks'] = { name = [[keepmarks]], desc = [[following command keeps marks where they are]] },
  [':keepjumps'] = { name = [[keepjumps]], desc = [[following command keeps jumplist and marks]] },
  [':keeppatterns'] = {
    name = [[keeppatterns]],
    desc = [[following command keeps search pattern history]],
    command = true,
  },
  [':lNext'] = { name = [[lNext]], desc = [[go to previous entry in location list]] },
  [':lNfile'] = { name = [[lNfile]], desc = [[go to last entry in previous file]] },
  [':list'] = { name = [[list]], desc = [[print lines]] },
  [':labove'] = { name = [[labove]], desc = [[go to location above current line]] },
  [':laddexpr'] = { name = [[laddexpr]], desc = [[add locations from expr]] },
  [':laddbuffer'] = { name = [[laddbuffer]], desc = [[add locations from buffer]] },
  [':laddfile'] = { name = [[laddfile]], desc = [[add locations to current location list]] },
  [':lafter'] = { name = [[lafter]], desc = [[go to location after current cursor]] },
  [':last'] = { name = [[last]], desc = [[go to the last file in the argument list]] },
  [':language'] = { name = [[language]], desc = [[set the language (locale)]] },
  [':later'] = { name = [[later]], desc = [[go to newer change, redo]] },
  [':lbefore'] = { name = [[lbefore]], desc = [[go to location before current cursor]] },
  [':lbelow'] = { name = [[lbelow]], desc = [[go to location below current line]] },
  [':lbottom'] = { name = [[lbottom]], desc = [[scroll to the bottom of the location window]] },
  [':lbuffer'] = { name = [[lbuffer]], desc = [[parse locations and jump to first location]] },
  [':lcd'] = { name = [[lcd]], desc = [[change directory locally]] },
  [':lchdir'] = { name = [[lchdir]], desc = [[change directory locally]] },
  [':lclose'] = { name = [[lclose]], desc = [[close location window]] },
  [':ldo'] = { name = [[ldo]], desc = [[execute command in valid location list entries]] },
  [':lfdo'] = { name = [[lfdo]], desc = [[execute command in each file in location list]] },
  [':left'] = { name = [[left]], desc = [[left align lines]] },
  [':leftabove'] = { name = [[leftabove]], desc = [[make split window appear left or above]] },
  [':let'] = { name = [[let]], desc = [[assign a value to a variable or option]] },
  [':lexpr'] = { name = [[lexpr]], desc = [[read locations from expr and jump to first]] },
  [':lfile'] = { name = [[lfile]], desc = [[read file with locations and jump to first]] },
  [':lfirst'] = { name = [[lfirst]], desc = [[go to the specified location, default first one]] },
  [':lgetbuffer'] = { name = [[lgetbuffer]], desc = [[get locations from buffer]] },
  [':lgetexpr'] = { name = [[lgetexpr]], desc = [[get locations from expr]] },
  [':lgetfile'] = { name = [[lgetfile]], desc = [[read file with locations]] },
  [':lgrep'] = { name = [[lgrep]], desc = [[run 'grepprg' and jump to first match]] },
  [':lgrepadd'] = { name = [[lgrepadd]], desc = [[like :grep, but append to current list]] },
  [':lhelpgrep'] = { name = [[lhelpgrep]], desc = [[like ":helpgrep" but uses location list]] },
  [':lhistory'] = { name = [[lhistory]], desc = [[list the location lists]] },
  [':ll'] = { name = [[ll]], desc = [[go to specific location]] },
  [':llast'] = { name = [[llast]], desc = [[go to the specified location, default last one]] },
  [':llist'] = { name = [[llist]], desc = [[list all locations]] },
  [':lmake'] = {
    name = [[lmake]],
    desc = [[execute external command 'makeprg' and parse error messages]],
    command = true,
  },
  [':lmap'] = { name = [[lmap]], desc = [[like ":map!" but includes Lang-Arg mode]] },
  [':lmapclear'] = { name = [[lmapclear]], desc = [[like ":mapclear!" but includes Lang-Arg mode]] },
  [':lnext'] = { name = [[lnext]], desc = [[go to next location]] },
  [':lnewer'] = { name = [[lnewer]], desc = [[go to newer location list]] },
  [':lnfile'] = { name = [[lnfile]], desc = [[go to first location in next file]] },
  [':lnoremap'] = { name = [[lnoremap]], desc = [[like ":noremap!" but includes Lang-Arg mode]] },
  [':loadkeymap'] = { name = [[loadkeymap]], desc = [[load the following keymaps until EOF]] },
  [':loadview'] = { name = [[loadview]], desc = [[load view for current window from a file]] },
  [':lockmarks'] = { name = [[lockmarks]], desc = [[following command keeps marks where they are]] },
  [':lockvar'] = { name = [[lockvar]], desc = [[lock variables]] },
  [':lolder'] = { name = [[lolder]], desc = [[go to older location list]] },
  [':lopen'] = { name = [[lopen]], desc = [[open location window]] },
  [':lprevious'] = { name = [[lprevious]], desc = [[go to previous location]] },
  [':lpfile'] = { name = [[lpfile]], desc = [[go to last location in previous file]] },
  [':lrewind'] = { name = [[lrewind]], desc = [[go to the specified location, default first one]] },
  [':ls'] = { name = [[ls]], desc = [[list all buffers]] },
  [':ltag'] = { name = [[ltag]], desc = [[jump to tag and add matching tags to the location list]] },
  [':lunmap'] = { name = [[lunmap]], desc = [[like ":unmap!" but includes Lang-Arg mode]] },
  [':lua'] = { name = [[lua]], desc = [[execute |Lua| command]] },
  [':luado'] = { name = [[luado]], desc = [[execute Lua command for each line]] },
  [':luafile'] = { name = [[luafile]], desc = [[execute |Lua| script file]] },
  [':lvimgrep'] = { name = [[lvimgrep]], desc = [[search for pattern in files]] },
  [':lvimgrepadd'] = { name = [[lvimgrepadd]], desc = [[like :vimgrep, but append to current list]] },
  [':lwindow'] = { name = [[lwindow]], desc = [[open or close location window]] },
  [':move'] = { name = [[move]], desc = [[move lines]] },
  [':mark'] = { name = [[mark]], desc = [[set a mark]] },
  [':make'] = {
    name = [[make]],
    desc = [[execute external command 'makeprg' and parse error messages]],
    command = true,
  },
  [':map'] = { name = [[map]], desc = [[show or enter a mapping]] },
  [':mapclear'] = { name = [[mapclear]], desc = [[clear all mappings for Normal and Visual mode]] },
  [':marks'] = { name = [[marks]], desc = [[list all marks]] },
  [':match'] = { name = [[match]], desc = [[define a match to highlight]] },
  [':menu'] = { name = [[menu]], desc = [[enter a new menu item]] },
  [':menutranslate'] = { name = [[menutranslate]], desc = [[add a menu translation item]] },
  [':messages'] = { name = [[messages]], desc = [[view previously displayed messages]] },
  [':mkexrc'] = { name = [[mkexrc]], desc = [[write current mappings and settings to a file]] },
  [':mksession'] = { name = [[mksession]], desc = [[write session info to a file]] },
  [':mkspell'] = { name = [[mkspell]], desc = [[produce .spl spell file]] },
  [':mkvimrc'] = { name = [[mkvimrc]], desc = [[write current mappings and settings to a file]] },
  [':mkview'] = { name = [[mkview]], desc = [[write view of current window to a file]] },
  [':mode'] = { name = [[mode]], desc = [[show or change the screen mode]] },
  [':next'] = { name = [[next]], desc = [[go to next file in the argument list]] },
  [':new'] = { name = [[new]], desc = [[create a new empty window]] },
  [':nmap'] = { name = [[nmap]], desc = [[like ":map" but for Normal mode]] },
  [':nmapclear'] = { name = [[nmapclear]], desc = [[clear all mappings for Normal mode]] },
  [':nmenu'] = { name = [[nmenu]], desc = [[add menu for Normal mode]] },
  [':nnoremap'] = { name = [[nnoremap]], desc = [[like ":noremap" but for Normal mode]] },
  [':nnoremenu'] = { name = [[nnoremenu]], desc = [[like ":noremenu" but for Normal mode]] },
  [':noautocmd'] = { name = [[noautocmd]], desc = [[following commands don't trigger autocommands]] },
  [':noremap'] = { name = [[noremap]], desc = [[enter a mapping that will not be remapped]] },
  [':nohlsearch'] = { name = [[nohlsearch]], desc = [[suspend 'hlsearch' highlighting]] },
  [':noreabbrev'] = {
    name = [[noreabbrev]],
    desc = [[enter an abbreviation that will not be remapped]],
    command = true,
  },
  [':noremenu'] = { name = [[noremenu]], desc = [[enter a menu that will not be remapped]] },
  [':normal'] = { name = [[normal]], desc = [[execute Normal mode commands]] },
  [':noswapfile'] = { name = [[noswapfile]], desc = [[following commands don't create a swap file]] },
  [':number'] = { name = [[number]], desc = [[print lines with line number]] },
  [':nunmap'] = { name = [[nunmap]], desc = [[like ":unmap" but for Normal mode]] },
  [':nunmenu'] = { name = [[nunmenu]], desc = [[remove menu for Normal mode]] },
  [':oldfiles'] = { name = [[oldfiles]], desc = [[list files that have marks in the |shada| file]] },
  [':omap'] = { name = [[omap]], desc = [[like ":map" but for Operator-pending mode]] },
  [':omapclear'] = { name = [[omapclear]], desc = [[remove all mappings for Operator-pending mode]] },
  [':omenu'] = { name = [[omenu]], desc = [[add menu for Operator-pending mode]] },
  [':only'] = { name = [[only]], desc = [[close all windows except the current one]] },
  [':onoremap'] = { name = [[onoremap]], desc = [[like ":noremap" but for Operator-pending mode]] },
  [':onoremenu'] = { name = [[onoremenu]], desc = [[like ":noremenu" but for Operator-pending mode]] },
  [':options'] = { name = [[options]], desc = [[open the options-window]] },
  [':ounmap'] = { name = [[ounmap]], desc = [[like ":unmap" but for Operator-pending mode]] },
  [':ounmenu'] = { name = [[ounmenu]], desc = [[remove menu for Operator-pending mode]] },
  [':ownsyntax'] = { name = [[ownsyntax]], desc = [[set new local syntax highlight for this window]] },
  [':packadd'] = { name = [[packadd]], desc = [[add a plugin from 'packpath']] },
  [':packloadall'] = { name = [[packloadall]], desc = [[load all packages under 'packpath']] },
  [':pclose'] = { name = [[pclose]], desc = [[close preview window]] },
  [':pedit'] = { name = [[pedit]], desc = [[edit file in the preview window]] },
  [':perl'] = { name = [[perl]], desc = [[execute perl command]] },
  [':perldo'] = { name = [[perldo]], desc = [[execute perl command for each line]] },
  [':perlfile'] = { name = [[perlfile]], desc = [[execute perl script file]] },
  [':print'] = { name = [[print]], desc = [[print lines]] },
  [':profdel'] = { name = [[profdel]], desc = [[stop profiling a function or script]] },
  [':profile'] = { name = [[profile]], desc = [[profiling functions and scripts]] },
  [':pop'] = { name = [[pop]], desc = [[jump to older entry in tag stack]] },
  [':popup'] = { name = [[popup]], desc = [[popup a menu by name]] },
  [':ppop'] = { name = [[ppop]], desc = [[":pop" in preview window]] },
  [':preserve'] = { name = [[preserve]], desc = [[write all text to swap file]] },
  [':previous'] = { name = [[previous]], desc = [[go to previous file in argument list]] },
  [':psearch'] = { name = [[psearch]], desc = [[like ":ijump" but shows match in preview window]] },
  [':ptag'] = { name = [[ptag]], desc = [[show tag in preview window]] },
  -- [':ptNext|	:ptN[ext]	'] = { name = [[ptNext|	:ptN[ext]	]], desc = [[in preview window]] },
  -- [':ptfirst|	:ptf[irst]	'] = { name = [[ptfirst|	:ptf[irst]	]], desc = [[in preview window]] },
  -- [':ptjump|	:ptj[ump]	'] = { name = [[ptjump|	:ptj[ump]	]], desc = [[and show tag in preview window]] },
  -- [':ptlast|	:ptl[ast]	'] = { name = [[ptlast|	:ptl[ast]	]], desc = [[in preview window]] },
  -- [':ptnext|	:ptn[ext]	'] = { name = [[ptnext|	:ptn[ext]	]], desc = [[in preview window]] },
  -- [':ptprevious|	:ptp[revious]	'] = {
  --   name = [[ptprevious|	:ptp[revious]	]],
  --   desc = [[in preview window]],
  --   command = true,
  -- },
  -- [':ptrewind|	:ptr[ewind]	'] = { name = [[ptrewind|	:ptr[ewind]	]], desc = [[in preview window]] },
  -- [':ptselect|	:pts[elect]	'] = {
  --   name = [[ptselect|	:pts[elect]	]],
  --   desc = [[and show tag in preview window]],
  --   command = true,
  -- },
  [':put'] = { name = [[put]], desc = [[insert contents of register in the text]] },
  [':pwd'] = { name = [[pwd]], desc = [[print current directory]] },
  [':py3'] = { name = [[py3]], desc = [[execute Python 3 command]] },
  [':python3'] = { name = [[python3]], desc = [[same as :py3]] },
  [':py3do'] = { name = [[py3do]], desc = [[execute Python 3 command for each line]] },
  [':py3file'] = { name = [[py3file]], desc = [[execute Python 3 script file]] },
  [':python'] = { name = [[python]], desc = [[execute Python command]] },
  [':pydo'] = { name = [[pydo]], desc = [[execute Python command for each line]] },
  [':pyfile'] = { name = [[pyfile]], desc = [[execute Python script file]] },
  [':pyx'] = { name = [[pyx]], desc = [[execute |python_x| command]] },
  [':pythonx'] = { name = [[pythonx]], desc = [[same as :pyx]] },
  [':pyxdo'] = { name = [[pyxdo]], desc = [[execute |python_x| command for each line]] },
  [':pyxfile'] = { name = [[pyxfile]], desc = [[execute |python_x| script file]] },
  [':quit'] = { name = [[quit]], desc = [[quit current window (when one window quit Vim)]] },
  [':quitall'] = { name = [[quitall]], desc = [[quit Vim]] },
  [':qall'] = { name = [[qall]], desc = [[quit Vim]] },
  [':read'] = { name = [[read]], desc = [[read file into the text]] },
  [':recover'] = { name = [[recover]], desc = [[recover a file from a swap file]] },
  [':redo'] = { name = [[redo]], desc = [[redo one undone change]] },
  [':redir'] = { name = [[redir]], desc = [[redirect messages to a file or register]] },
  [':redraw'] = { name = [[redraw]], desc = [[force a redraw of the display]] },
  [':redrawstatus'] = {
    name = [[redrawstatus]],
    desc = [[force a redraw of the status line(s) and window bar(s)]],
    command = true,
  },
  [':redrawtabline'] = { name = [[redrawtabline]], desc = [[force a redraw of the tabline]] },
  [':registers'] = { name = [[registers]], desc = [[display the contents of registers]] },
  [':resize'] = { name = [[resize]], desc = [[change current window height]] },
  [':retab'] = { name = [[retab]], desc = [[change tab size]] },
  [':return'] = { name = [[return]], desc = [[return from a user function]] },
  [':rewind'] = { name = [[rewind]], desc = [[go to the first file in the argument list]] },
  [':right'] = { name = [[right]], desc = [[right align text]] },
  [':rightbelow'] = { name = [[rightbelow]], desc = [[make split window appear right or below]] },
  [':rshada'] = { name = [[rshada]], desc = [[read from |shada| file]] },
  [':ruby'] = { name = [[ruby]], desc = [[execute Ruby command]] },
  [':rubydo'] = { name = [[rubydo]], desc = [[execute Ruby command for each line]] },
  [':rubyfile'] = { name = [[rubyfile]], desc = [[execute Ruby script file]] },
  [':rundo'] = { name = [[rundo]], desc = [[read undo information from a file]] },
  [':runtime'] = { name = [[runtime]], desc = [[source vim scripts in 'runtimepath']] },
  [':substitute'] = { name = [[substitute]], desc = [[find and replace text]] },
  [':sNext'] = { name = [[sNext]], desc = [[split window and go to previous file in argument list]] },
  [':sandbox'] = { name = [[sandbox]], desc = [[execute a command in the sandbox]] },
  [':sargument'] = {
    name = [[sargument]],
    desc = [[split window and go to specific file in argument list]],
    command = true,
  },
  [':sall'] = { name = [[sall]], desc = [[open a window for each file in argument list]] },
  [':saveas'] = { name = [[saveas]], desc = [[save file under another name.]] },
  [':sbuffer'] = {
    name = [[sbuffer]],
    desc = [[split window and go to specific file in the buffer list]],
    command = true,
  },
  [':sbNext'] = {
    name = [[sbNext]],
    desc = [[split window and go to previous file in the buffer list]],
    command = true,
  },
  [':sball'] = { name = [[sball]], desc = [[open a window for each file in the buffer list]] },
  [':sbfirst'] = { name = [[sbfirst]], desc = [[split window and go to first file in the buffer list]] },
  [':sblast'] = { name = [[sblast]], desc = [[split window and go to last file in buffer list]] },
  [':sbmodified'] = {
    name = [[sbmodified]],
    desc = [[split window and go to modified file in the buffer list]],
    command = true,
  },
  [':sbnext'] = { name = [[sbnext]], desc = [[split window and go to next file in the buffer list]] },
  [':sbprevious'] = {
    name = [[sbprevious]],
    desc = [[split window and go to previous file in the buffer list]],
    command = true,
  },
  [':sbrewind'] = {
    name = [[sbrewind]],
    desc = [[split window and go to first file in the buffer list]],
    command = true,
  },
  [':scriptnames'] = { name = [[scriptnames]], desc = [[list names of all sourced Vim scripts]] },
  [':scriptencoding'] = { name = [[scriptencoding]], desc = [[encoding used in sourced Vim script]] },
  [':set'] = { name = [[set]], desc = [[show or set options]] },
  [':setfiletype'] = { name = [[setfiletype]], desc = [[set 'filetype', unless it was set already]] },
  [':setglobal'] = { name = [[setglobal]], desc = [[show global values of options]] },
  [':setlocal'] = { name = [[setlocal]], desc = [[show or set options locally]] },
  [':sfind'] = { name = [[sfind]], desc = [[split current window and edit file in 'path']] },
  [':sfirst'] = { name = [[sfirst]], desc = [[split window and go to first file in the argument list]] },
  [':sign'] = { name = [[sign]], desc = [[manipulate signs]] },
  [':silent'] = { name = [[silent]], desc = [[run a command silently]] },
  [':sleep'] = { name = [[sleep]], desc = [[do nothing for a few seconds]] },
  [':slast'] = { name = [[slast]], desc = [[split window and go to last file in the argument list]] },
  [':smagic'] = { name = [[smagic]], desc = [[:substitute with 'magic']] },
  [':smap'] = { name = [[smap]], desc = [[like ":map" but for Select mode]] },
  [':smapclear'] = { name = [[smapclear]], desc = [[remove all mappings for Select mode]] },
  [':smenu'] = { name = [[smenu]], desc = [[add menu for Select mode]] },
  [':snext'] = { name = [[snext]], desc = [[split window and go to next file in the argument list]] },
  [':snomagic'] = { name = [[snomagic]], desc = [[:substitute with 'nomagic']] },
  [':snoremap'] = { name = [[snoremap]], desc = [[like ":noremap" but for Select mode]] },
  [':snoremenu'] = { name = [[snoremenu]], desc = [[like ":noremenu" but for Select mode]] },
  [':sort'] = { name = [[sort]], desc = [[sort lines]] },
  [':source'] = { name = [[source]], desc = [[read Vim or Ex commands from a file]] },
  [':spelldump'] = { name = [[spelldump]], desc = [[split window and fill with all correct words]] },
  [':spellgood'] = { name = [[spellgood]], desc = [[add good word for spelling]] },
  [':spellinfo'] = { name = [[spellinfo]], desc = [[show info about loaded spell files]] },
  [':spellrare'] = { name = [[spellrare]], desc = [[add rare word for spelling]] },
  [':spellrepall'] = { name = [[spellrepall]], desc = [[replace all bad words like last |z=|]] },
  [':spellundo'] = { name = [[spellundo]], desc = [[remove good or bad word]] },
  [':spellwrong'] = { name = [[spellwrong]], desc = [[add spelling mistake]] },
  [':split'] = { name = [[split]], desc = [[split current window]] },
  [':sprevious'] = {
    name = [[sprevious]],
    desc = [[split window and go to previous file in the argument list]],
    command = true,
  },
  [':srewind'] = {
    name = [[srewind]],
    desc = [[split window and go to first file in the argument list]],
    command = true,
  },
  [':stop'] = { name = [[stop]], desc = [[suspend the editor or escape to a shell]] },
  [':stag'] = { name = [[stag]], desc = [[split window and jump to a tag]] },
  [':startinsert'] = { name = [[startinsert]], desc = [[start Insert mode]] },
  [':startgreplace'] = { name = [[startgreplace]], desc = [[start Virtual Replace mode]] },
  [':startreplace'] = { name = [[startreplace]], desc = [[start Replace mode]] },
  [':stopinsert'] = { name = [[stopinsert]], desc = [[stop Insert mode]] },
  [':stjump'] = { name = [[stjump]], desc = [[do ":tjump" and split window]] },
  [':stselect'] = { name = [[stselect]], desc = [[do ":tselect" and split window]] },
  [':sunhide'] = { name = [[sunhide]], desc = [[same as ":unhide"]] },
  [':sunmap'] = { name = [[sunmap]], desc = [[like ":unmap" but for Select mode]] },
  [':sunmenu'] = { name = [[sunmenu]], desc = [[remove menu for Select mode]] },
  [':suspend'] = { name = [[suspend]], desc = [[same as ":stop"]] },
  [':sview'] = { name = [[sview]], desc = [[split window and edit file read-only]] },
  [':swapname'] = { name = [[swapname]], desc = [[show the name of the current swap file]] },
  [':syntax'] = { name = [[syntax]], desc = [[syntax highlighting]] },
  [':syntime'] = { name = [[syntime]], desc = [[measure syntax highlighting speed]] },
  [':syncbind'] = { name = [[syncbind]], desc = [[sync scroll binding]] },
  [':t'] = { name = [[t]], desc = [[same as ":copy"]] },
  [':tNext'] = { name = [[tNext]], desc = [[jump to previous matching tag]] },
  [':tabNext'] = { name = [[tabNext]], desc = [[go to previous tab page]] },
  [':tabclose'] = { name = [[tabclose]], desc = [[close current tab page]] },
  [':tabdo'] = { name = [[tabdo]], desc = [[execute command in each tab page]] },
  [':tabedit'] = { name = [[tabedit]], desc = [[edit a file in a new tab page]] },
  [':tabfind'] = { name = [[tabfind]], desc = [[find file in 'path', edit it in a new tab page]] },
  [':tabfirst'] = { name = [[tabfirst]], desc = [[go to first tab page]] },
  [':tablast'] = { name = [[tablast]], desc = [[go to last tab page]] },
  [':tabmove'] = { name = [[tabmove]], desc = [[move tab page to other position]] },
  [':tabnew'] = { name = [[tabnew]], desc = [[edit a file in a new tab page]] },
  [':tabnext'] = { name = [[tabnext]], desc = [[go to next tab page]] },
  [':tabonly'] = { name = [[tabonly]], desc = [[close all tab pages except the current one]] },
  [':tabprevious'] = { name = [[tabprevious]], desc = [[go to previous tab page]] },
  [':tabrewind'] = { name = [[tabrewind]], desc = [[go to first tab page]] },
  [':tabs'] = { name = [[tabs]], desc = [[list the tab pages and what they contain]] },
  [':tab'] = { name = [[tab]], desc = [[create new tab when opening new window]] },
  [':tag'] = { name = [[tag]], desc = [[jump to tag]] },
  [':tags'] = { name = [[tags]], desc = [[show the contents of the tag stack]] },
  [':tcd'] = { name = [[tcd]], desc = [[change directory for tab page]] },
  [':tchdir'] = { name = [[tchdir]], desc = [[change directory for tab page]] },
  [':terminal'] = { name = [[terminal]], desc = [[open a terminal buffer]] },
  [':tfirst'] = { name = [[tfirst]], desc = [[jump to first matching tag]] },
  [':throw'] = { name = [[throw]], desc = [[throw an exception]] },
  [':tjump'] = {
    name = [[tjump]],
    desc = [[like ":tselect", but jump directly when there is only one match]],
    command = true,
  },
  [':tlast'] = { name = [[tlast]], desc = [[jump to last matching tag]] },
  [':tlmenu'] = { name = [[tlmenu]], desc = [[add menu for |Terminal-mode|]] },
  [':tlnoremenu'] = { name = [[tlnoremenu]], desc = [[like ":noremenu" but for |Terminal-mode|]] },
  [':tlunmenu'] = { name = [[tlunmenu]], desc = [[remove menu for |Terminal-mode|]] },
  [':tmapclear'] = { name = [[tmapclear]], desc = [[remove all mappings for |Terminal-mode|]] },
  [':tmap'] = { name = [[tmap]], desc = [[like ":map" but for |Terminal-mode|]] },
  [':tmenu'] = { name = [[tmenu]], desc = [[define menu tooltip]] },
  [':tnext'] = { name = [[tnext]], desc = [[jump to next matching tag]] },
  [':tnoremap'] = { name = [[tnoremap]], desc = [[like ":noremap" but for |Terminal-mode|]] },
  [':topleft'] = { name = [[topleft]], desc = [[make split window appear at top or far left]] },
  [':tprevious'] = { name = [[tprevious]], desc = [[jump to previous matching tag]] },
  [':trewind'] = { name = [[trewind]], desc = [[jump to first matching tag]] },
  [':trust'] = { name = [[trust]], desc = [[add or remove file from trust database]] },
  [':try'] = { name = [[try]], desc = [[execute commands, abort on error or exception]] },
  [':tselect'] = { name = [[tselect]], desc = [[list matching tags and select one]] },
  [':tunmap'] = { name = [[tunmap]], desc = [[like ":unmap" but for |Terminal-mode|]] },
  [':tunmenu'] = { name = [[tunmenu]], desc = [[remove menu tooltip]] },
  [':undo'] = { name = [[undo]], desc = [[undo last change(s)]] },
  [':undojoin'] = { name = [[undojoin]], desc = [[join next change with previous undo block]] },
  [':undolist'] = { name = [[undolist]], desc = [[list leafs of the undo tree]] },
  [':unabbreviate'] = { name = [[unabbreviate]], desc = [[remove abbreviation]] },
  [':unhide'] = { name = [[unhide]], desc = [[open a window for each loaded file in the buffer list]] },
  [':unlet'] = { name = [[unlet]], desc = [[delete variable]] },
  [':unlockvar'] = { name = [[unlockvar]], desc = [[unlock variables]] },
  [':unmap'] = { name = [[unmap]], desc = [[remove mapping]] },
  [':unmenu'] = { name = [[unmenu]], desc = [[remove menu]] },
  [':unsilent'] = { name = [[unsilent]], desc = [[run a command not silently]] },
  [':update'] = { name = [[update]], desc = [[write buffer if modified]] },
  [':vglobal'] = { name = [[vglobal]], desc = [[execute commands for not matching lines]] },
  [':version'] = { name = [[version]], desc = [[print version number and other info]] },
  [':verbose'] = { name = [[verbose]], desc = [[execute command with 'verbose' set]] },
  [':vertical'] = { name = [[vertical]], desc = [[make following command split vertically]] },
  [':vimgrep'] = { name = [[vimgrep]], desc = [[search for pattern in files]] },
  [':vimgrepadd'] = { name = [[vimgrepadd]], desc = [[like :vimgrep, but append to current list]] },
  [':visual'] = { name = [[visual]], desc = [[same as ":edit", but turns off "Ex" mode]] },
  [':viusage'] = { name = [[viusage]], desc = [[overview of Normal mode commands]] },
  [':view'] = { name = [[view]], desc = [[edit a file read-only]] },
  [':vmap'] = { name = [[vmap]], desc = [[like ":map" but for Visual+Select mode]] },
  [':vmapclear'] = { name = [[vmapclear]], desc = [[remove all mappings for Visual+Select mode]] },
  [':vmenu'] = { name = [[vmenu]], desc = [[add menu for Visual+Select mode]] },
  [':vnew'] = { name = [[vnew]], desc = [[create a new empty window, vertically split]] },
  [':vnoremap'] = { name = [[vnoremap]], desc = [[like ":noremap" but for Visual+Select mode]] },
  [':vnoremenu'] = { name = [[vnoremenu]], desc = [[like ":noremenu" but for Visual+Select mode]] },
  [':vsplit'] = { name = [[vsplit]], desc = [[split current window vertically]] },
  [':vunmap'] = { name = [[vunmap]], desc = [[like ":unmap" but for Visual+Select mode]] },
  [':vunmenu'] = { name = [[vunmenu]], desc = [[remove menu for Visual+Select mode]] },
  [':windo'] = { name = [[windo]], desc = [[execute command in each window]] },
  [':write'] = { name = [[write]], desc = [[write to a file]] },
  [':wNext'] = { name = [[wNext]], desc = [[write to a file and go to previous file in argument list]] },
  [':wall'] = { name = [[wall]], desc = [[write all (changed) buffers]] },
  [':while'] = { name = [[while]], desc = [[execute loop for as long as condition met]] },
  [':winsize'] = { name = [[winsize]], desc = [[get or set window size (obsolete)]] },
  [':wincmd'] = { name = [[wincmd]], desc = [[execute a Window (CTRL-W) command]] },
  [':winpos'] = { name = [[winpos]], desc = [[get or set window position]] },
  [':wnext'] = { name = [[wnext]], desc = [[write to a file and go to next file in argument list]] },
  [':wprevious'] = {
    name = [[wprevious]],
    desc = [[write to a file and go to previous file in argument list]],
    command = true,
  },
  [':wq'] = { name = [[wq]], desc = [[write to a file and quit window or Vim]] },
  [':wqall'] = { name = [[wqall]], desc = [[write all changed buffers and quit Vim]] },
  [':wshada'] = { name = [[wshada]], desc = [[write to ShaDa file]] },
  [':wundo'] = { name = [[wundo]], desc = [[write undo information to a file]] },
  [':xit'] = { name = [[xit]], desc = [[write if buffer changed and close window]] },
  [':xall'] = { name = [[xall]], desc = [[same as ":wqall"]] },
  [':xmapclear'] = { name = [[xmapclear]], desc = [[remove all mappings for Visual mode]] },
  [':xmap'] = { name = [[xmap]], desc = [[like ":map" but for Visual mode]] },
  [':xmenu'] = { name = [[xmenu]], desc = [[add menu for Visual mode]] },
  [':xnoremap'] = { name = [[xnoremap]], desc = [[like ":noremap" but for Visual mode]] },
  [':xnoremenu'] = { name = [[xnoremenu]], desc = [[like ":noremenu" but for Visual mode]] },
  [':xunmap'] = { name = [[xunmap]], desc = [[like ":unmap" but for Visual mode]] },
  [':xunmenu'] = { name = [[xunmenu]], desc = [[remove menu for Visual mode]] },
  [':yank'] = { name = [[yank]], desc = [[yank lines into a register]] },
  [':z'] = { name = [[z]], desc = [[print some lines]] },
  [':~'] = { name = [[~]], desc = [[repeat last ":substitute"]] },
}

local commands = {
  'copy',
  'grep',
  'doautoall',
  'doautocmd',
  'delmarks',
  'delfunction',
  'delcommand',
  'debug',
  'const',
  'continue',
  'compiler',
  'command',
  'colorscheme',
  'copy',
  'cmap',
  'cfdo',
  'cdo',
  'cd',
  'call',
  'change',
  'badd',
  'argedit',
  'argadd',
  'anoremenu',
  'amenu',
  'abbreviate',
  '@',
  '&',
  '!!',
  '!',
}

---@param opts CommandPalConfig
function M:__override_builtins(opts)
  for _, v in ipairs(commands) do
    self.builtin[':' .. v].command = true
  end
end

---@param opts CommandPalConfig
---@return palette.MappedAction
function M:__map_builtins(opts)
  self:__override_builtins(opts)
  local builtin = {}

  for k, v in pairs(self.builtin) do
    if not v.bang and opts.builtin.bang == false then
      builtin[k] = {
        name = v.name,
        group = v.group or 'Vim',
        desc = v.desc,
        command = (function()
          if type(v.command) == 'boolean' and v.command then
            return set_cmd(k .. ' ')
          else
            return k
          end
        end)(),
        cmd_str = k,
        handler = default_handler,
        ordinal = get_ordinal(v, opts),
      }
    end
  end

  return builtin
end

function M.get_items(opts) return M:__map_builtins(opts) end

return M
