local get_ordinal = require('command_pal.ordinal').get_ordinal
local default_handler = require('command_pal.handler').default_handler
local set_cmd = require('command_pal.utils').set_cmdline

---@class provider.Builtin : provider.Base
---@field builtin builtin.BuiltinT
local M = {}

---@class builtin.Value
---@field name string
---@field desc string
---@field bang? boolean
---@field command? boolean
---@field ordinal? string

---@class builtin.BuiltinT
---@field [string] builtin.Value

-- TODO: use scripte for this
--
-- '<,'>s/|:\(.*\)|\s*:\S*\s*\(.*\)/[":\1"]={name=[[\1]], desc = [[\2]], command = true},
M.builtin = {
  [':range'] = { name = [[range]], desc = [[go to last line in {range}]], command = true },
  [':!'] = { name = [[!]], desc = [[filter lines or execute an external command]], command = true },
  [':!!'] = { name = [[!!]], desc = [[repeat last ":!" command]], command = true },
  [':#'] = { name = [[#]], desc = [[same as ":number"]], command = true },
  [':&'] = { name = [[&]], desc = [[repeat last ":substitute"]], command = true },
  [':star'] = { name = [[star]], desc = [[use the last Visual area, like ":'<,'>"]], command = true },
  [':<'] = { name = [[<]], desc = [[shift lines one 'shiftwidth' left]], command = true },
  [':='] = { name = [[=]], desc = [[print the last line number]], command = true },
  [':>'] = { name = [[>]], desc = [[shift lines one 'shiftwidth' right]], command = true },
  [':@'] = { name = [[@]], desc = [[execute contents of a register]], command = true },
  [':@@'] = { name = [[@@]], desc = [[repeat the previous ":@"]], command = true },
  [':2match'] = { name = [[2match]], desc = [[define a second match to highlight]], command = true },
  [':3match'] = { name = [[3match]], desc = [[define a third match to highlight]], command = true },
  [':Next'] = { name = [[Next]], desc = [[go to previous file in the argument list]], command = true },
  [':append'] = { name = [[append]], desc = [[append text]], command = true },
  [':abbreviate'] = { name = [[abbreviate]], desc = [[enter abbreviation]], command = true },
  [':abclear'] = { name = [[abclear]], desc = [[remove all abbreviations]], command = true },
  [':aboveleft'] = { name = [[aboveleft]], desc = [[make split window appear left or above]], command = true },
  [':all'] = { name = [[all]], desc = [[open a window for each file in the argument list]], command = true },
  [':amenu'] = { name = [[amenu]], desc = [[enter new menu item for all modes]], command = true },
  [':anoremenu'] = {
    name = [[anoremenu]],
    desc = [[enter a new menu for all modes that will not be remapped]],
    command = true,
  },
  [':args'] = { name = [[args]], desc = [[print the argument list]], command = true },
  [':argadd'] = { name = [[argadd]], desc = [[add items to the argument list]], command = true },
  [':argdedupe'] = { name = [[argdedupe]], desc = [[remove duplicates from the argument list]], command = true },
  [':argdelete'] = { name = [[argdelete]], desc = [[delete items from the argument list]], command = true },
  [':argedit'] = { name = [[argedit]], desc = [[add item to the argument list and edit it]], command = true },
  [':argdo'] = { name = [[argdo]], desc = [[do a command on all items in the argument list]], command = true },
  [':argglobal'] = { name = [[argglobal]], desc = [[define the global argument list]], command = true },
  [':arglocal'] = { name = [[arglocal]], desc = [[define a local argument list]], command = true },
  [':argument'] = { name = [[argument]], desc = [[go to specific file in the argument list]], command = true },
  [':ascii'] = { name = [[ascii]], desc = [[print ascii value of character under the cursor]], command = true },
  [':autocmd'] = { name = [[autocmd]], desc = [[enter or show autocommands]], command = true },
  [':augroup'] = { name = [[augroup]], desc = [[select the autocommand group to use]], command = true },
  [':aunmenu'] = { name = [[aunmenu]], desc = [[remove menu for all modes]], command = true },
  [':buffer'] = { name = [[buffer]], desc = [[go to specific buffer in the buffer list]], command = true },
  [':bNext'] = { name = [[bNext]], desc = [[go to previous buffer in the buffer list]], command = true },
  [':ball'] = { name = [[ball]], desc = [[open a window for each buffer in the buffer list]], command = true },
  [':badd'] = { name = [[badd]], desc = [[add buffer to the buffer list]], command = true },
  [':balt'] = { name = [[balt]], desc = [[like ":badd" but also set the alternate file]], command = true },
  [':bdelete'] = { name = [[bdelete]], desc = [[remove a buffer from the buffer list]], command = true },
  [':belowright'] = { name = [[belowright]], desc = [[make split window appear right or below]], command = true },
  [':bfirst'] = { name = [[bfirst]], desc = [[go to first buffer in the buffer list]], command = true },
  [':blast'] = { name = [[blast]], desc = [[go to last buffer in the buffer list]], command = true },
  [':bmodified'] = {
    name = [[bmodified]],
    desc = [[go to next buffer in the buffer list that has been modified]],
    command = true,
  },
  [':bnext'] = { name = [[bnext]], desc = [[go to next buffer in the buffer list]], command = true },
  [':botright'] = { name = [[botright]], desc = [[make split window appear at bottom or far right]], command = true },
  [':bprevious'] = { name = [[bprevious]], desc = [[go to previous buffer in the buffer list]], command = true },
  [':brewind'] = { name = [[brewind]], desc = [[go to first buffer in the buffer list]], command = true },
  [':break'] = { name = [[break]], desc = [[break out of while loop]], command = true },
  [':breakadd'] = { name = [[breakadd]], desc = [[add a debugger breakpoint]], command = true },
  [':breakdel'] = { name = [[breakdel]], desc = [[delete a debugger breakpoint]], command = true },
  [':breaklist'] = { name = [[breaklist]], desc = [[list debugger breakpoints]], command = true },
  [':browse'] = { name = [[browse]], desc = [[use file selection dialog]], command = true },
  [':bufdo'] = { name = [[bufdo]], desc = [[execute command in each listed buffer]], command = true },
  [':buffers'] = { name = [[buffers]], desc = [[list all files in the buffer list]], command = true },
  [':bunload'] = { name = [[bunload]], desc = [[unload a specific buffer]], command = true },
  [':bwipeout'] = { name = [[bwipeout]], desc = [[really delete a buffer]], command = true },
  [':change'] = { name = [[change]], desc = [[replace a line or series of lines]], command = true },
  [':cNext'] = { name = [[cNext]], desc = [[go to previous error]], command = true },
  [':cNfile'] = { name = [[cNfile]], desc = [[go to last error in previous file]], command = true },
  [':cabbrev'] = { name = [[cabbrev]], desc = [[like ":abbreviate" but for Command-line mode]], command = true },
  [':cabclear'] = { name = [[cabclear]], desc = [[clear all abbreviations for Command-line mode]], command = true },
  [':cabove'] = { name = [[cabove]], desc = [[go to error above current line]], command = true },
  [':caddbuffer'] = { name = [[caddbuffer]], desc = [[add errors from buffer]], command = true },
  [':caddexpr'] = { name = [[caddexpr]], desc = [[add errors from expr]], command = true },
  [':caddfile'] = { name = [[caddfile]], desc = [[add error message to current quickfix list]], command = true },
  [':cafter'] = { name = [[cafter]], desc = [[go to error after current cursor]], command = true },
  [':call'] = { name = [[call]], desc = [[call a function]], command = true },
  [':catch'] = { name = [[catch]], desc = [[part of a :try command]], command = true },
  [':cbefore'] = { name = [[cbefore]], desc = [[go to error before current cursor]], command = true },
  [':cbelow'] = { name = [[cbelow]], desc = [[go to error below current line]], command = true },
  [':cbottom'] = { name = [[cbottom]], desc = [[scroll to the bottom of the quickfix window]], command = true },
  [':cbuffer'] = { name = [[cbuffer]], desc = [[parse error messages and jump to first error]], command = true },
  [':cc'] = { name = [[cc]], desc = [[go to specific error]], command = true },
  [':cclose'] = { name = [[cclose]], desc = [[close quickfix window]], command = true },
  [':cd'] = { name = [[cd]], desc = [[change directory]], command = true },
  [':cdo'] = { name = [[cdo]], desc = [[execute command in each valid error list entry]], command = true },
  [':cfdo'] = { name = [[cfdo]], desc = [[execute command in each file in error list]], command = true },
  [':center'] = { name = [[center]], desc = [[format lines at the center]], command = true },
  [':cexpr'] = { name = [[cexpr]], desc = [[read errors from expr and jump to first]], command = true },
  [':cfile'] = { name = [[cfile]], desc = [[read file with error messages and jump to first]], command = true },
  [':cfirst'] = { name = [[cfirst]], desc = [[go to the specified error, default first one]], command = true },
  [':cgetbuffer'] = { name = [[cgetbuffer]], desc = [[get errors from buffer]], command = true },
  [':cgetexpr'] = { name = [[cgetexpr]], desc = [[get errors from expr]], command = true },
  [':cgetfile'] = { name = [[cgetfile]], desc = [[read file with error messages]], command = true },
  [':changes'] = { name = [[changes]], desc = [[print the change list]], command = true },
  [':chdir'] = { name = [[chdir]], desc = [[change directory]], command = true },
  [':checkhealth'] = { name = [[checkhealth]], desc = [[run healthchecks]], command = true },
  [':checkpath'] = { name = [[checkpath]], desc = [[list included files]], command = true },
  [':checktime'] = { name = [[checktime]], desc = [[check timestamp of loaded buffers]], command = true },
  [':chistory'] = { name = [[chistory]], desc = [[list the error lists]], command = true },
  [':clast'] = { name = [[clast]], desc = [[go to the specified error, default last one]], command = true },
  [':clearjumps'] = { name = [[clearjumps]], desc = [[clear the jump list]], command = true },
  [':clist'] = { name = [[clist]], desc = [[list all errors]], command = true },
  [':close'] = { name = [[close]], desc = [[close current window]], command = true },
  [':cmap'] = { name = [[cmap]], desc = [[like ":map" but for Command-line mode]], command = true },
  [':cmapclear'] = { name = [[cmapclear]], desc = [[clear all mappings for Command-line mode]], command = true },
  [':cmenu'] = { name = [[cmenu]], desc = [[add menu for Command-line mode]], command = true },
  [':cnext'] = { name = [[cnext]], desc = [[go to next error]], command = true },
  [':cnewer'] = { name = [[cnewer]], desc = [[go to newer error list]], command = true },
  [':cnfile'] = { name = [[cnfile]], desc = [[go to first error in next file]], command = true },
  [':cnoremap'] = { name = [[cnoremap]], desc = [[like ":noremap" but for Command-line mode]], command = true },
  [':cnoreabbrev'] = { name = [[cnoreabbrev]], desc = [[like ":noreabbrev" but for Command-line mode]], command = true },
  [':cnoremenu'] = { name = [[cnoremenu]], desc = [[like ":noremenu" but for Command-line mode]], command = true },
  [':copy'] = { name = [[copy]], desc = [[copy lines]], command = true },
  [':colder'] = { name = [[colder]], desc = [[go to older error list]], command = true },
  [':colorscheme'] = { name = [[colorscheme]], desc = [[load a specific color scheme]], command = true },
  [':command'] = { name = [[command]], desc = [[create user-defined command]], command = true },
  [':comclear'] = { name = [[comclear]], desc = [[clear all user-defined commands]], command = true },
  [':compiler'] = { name = [[compiler]], desc = [[do settings for a specific compiler]], command = true },
  [':continue'] = { name = [[continue]], desc = [[go back to :while]], command = true },
  [':confirm'] = { name = [[confirm]], desc = [[prompt user when confirmation required]], command = true },
  [':const'] = { name = [[const]], desc = [[create a variable as a constant]], command = true },
  [':copen'] = { name = [[copen]], desc = [[open quickfix window]], command = true },
  [':cprevious'] = { name = [[cprevious]], desc = [[go to previous error]], command = true },
  [':cpfile'] = { name = [[cpfile]], desc = [[go to last error in previous file]], command = true },
  [':cquit'] = { name = [[cquit]], desc = [[quit Vim with an error code]], command = true },
  [':crewind'] = { name = [[crewind]], desc = [[go to the specified error, default first one]], command = true },
  [':cunmap'] = { name = [[cunmap]], desc = [[like ":unmap" but for Command-line mode]], command = true },
  [':cunabbrev'] = { name = [[cunabbrev]], desc = [[like ":unabbrev" but for Command-line mode]], command = true },
  [':cunmenu'] = { name = [[cunmenu]], desc = [[remove menu for Command-line mode]], command = true },
  [':cwindow'] = { name = [[cwindow]], desc = [[open or close quickfix window]], command = true },
  [':delete'] = { name = [[delete]], desc = [[delete lines]], command = true },
  [':debug'] = { name = [[debug]], desc = [[run a command in debugging mode]], command = true },
  [':debuggreedy'] = { name = [[debuggreedy]], desc = [[read debug mode commands from normal input]], command = true },
  [':delcommand'] = { name = [[delcommand]], desc = [[delete user-defined command]], command = true },
  [':delfunction'] = { name = [[delfunction]], desc = [[delete a user function]], command = true },
  [':delmarks'] = { name = [[delmarks]], desc = [[delete marks]], command = true },
  [':diffupdate'] = { name = [[diffupdate]], desc = [[update 'diff' buffers]], command = true },
  [':diffget'] = { name = [[diffget]], desc = [[remove differences in current buffer]], command = true },
  [':diffoff'] = { name = [[diffoff]], desc = [[switch off diff mode]], command = true },
  [':diffpatch'] = { name = [[diffpatch]], desc = [[apply a patch and show differences]], command = true },
  [':diffput'] = { name = [[diffput]], desc = [[remove differences in other buffer]], command = true },
  [':diffsplit'] = { name = [[diffsplit]], desc = [[show differences with another file]], command = true },
  [':diffthis'] = { name = [[diffthis]], desc = [[make current window a diff window]], command = true },
  [':digraphs'] = { name = [[digraphs]], desc = [[show or enter digraphs]], command = true },
  [':display'] = { name = [[display]], desc = [[display registers]], command = true },
  [':djump'] = { name = [[djump]], desc = [[jump to #define]], command = true },
  [':dl|		:dl		short for '] = { name = [[dl|		:dl		short for ]], desc = [[with the 'l' flag]], command = true },
  [':dlist'] = { name = [[dlist]], desc = [[list #defines]], command = true },
  [':doautocmd'] = { name = [[doautocmd]], desc = [[apply autocommands to current buffer]], command = true },
  [':doautoall'] = { name = [[doautoall]], desc = [[apply autocommands for all loaded buffers]], command = true },
  [':dp|		:d[elete]p	short for '] = {
    name = [[dp|		:d[elete]p	short for ]],
    desc = [[with the 'p' flag]],
    command = true,
  },
  [':drop'] = { name = [[drop]], desc = [[jump to window editing file or edit file in current window]], command = true },
  [':dsearch'] = { name = [[dsearch]], desc = [[list one #define]], command = true },
  [':dsplit'] = { name = [[dsplit]], desc = [[split window and jump to #define]], command = true },
  [':edit'] = { name = [[edit]], desc = [[edit a file]], command = true },
  [':earlier'] = { name = [[earlier]], desc = [[go to older change, undo]], command = true },
  [':echo'] = { name = [[echo]], desc = [[echoes the result of expressions]], command = true },
  [':echoerr'] = { name = [[echoerr]], desc = [[like :echo, show like an error and use history]], command = true },
  [':echohl'] = { name = [[echohl]], desc = [[set highlighting for echo commands]], command = true },
  [':echomsg'] = { name = [[echomsg]], desc = [[same as :echo, put message in history]], command = true },
  [':echon'] = { name = [[echon]], desc = [[same as :echo, but without <EOL>]], command = true },
  [':else'] = { name = [[else]], desc = [[part of an :if command]], command = true },
  [':elseif'] = { name = [[elseif]], desc = [[part of an :if command]], command = true },
  [':emenu'] = { name = [[emenu]], desc = [[execute a menu by name]], command = true },
  [':endif'] = { name = [[endif]], desc = [[end previous :if]], command = true },
  [':endfor'] = { name = [[endfor]], desc = [[end previous :for]], command = true },
  [':endfunction'] = { name = [[endfunction]], desc = [[end of a user function started with :function]], command = true },
  [':endtry'] = { name = [[endtry]], desc = [[end previous :try]], command = true },
  [':endwhile'] = { name = [[endwhile]], desc = [[end previous :while]], command = true },
  [':enew'] = { name = [[enew]], desc = [[edit a new, unnamed buffer]], command = true },
  [':eval'] = { name = [[eval]], desc = [[evaluate an expression and discard the result]], command = true },
  [':ex'] = { name = [[ex]], desc = [[same as ":edit"]], command = true },
  [':execute'] = { name = [[execute]], desc = [[execute result of expressions]], command = true },
  [':exit'] = { name = [[exit]], desc = [[same as ":xit"]], command = true },
  [':exusage'] = { name = [[exusage]], desc = [[overview of Ex commands]], command = true },
  [':fclose'] = { name = [[fclose]], desc = [[close floating window]], command = true },
  [':file'] = { name = [[file]], desc = [[show or set the current file name]], command = true },
  [':files'] = { name = [[files]], desc = [[list all files in the buffer list]], command = true },
  [':filetype'] = { name = [[filetype]], desc = [[switch file type detection on/off]], command = true },
  [':filter'] = { name = [[filter]], desc = [[filter output of following command]], command = true },
  [':find'] = { name = [[find]], desc = [[find file in 'path' and edit it]], command = true },
  [':finally'] = { name = [[finally]], desc = [[part of a :try command]], command = true },
  [':finish'] = { name = [[finish]], desc = [[quit sourcing a Vim script]], command = true },
  [':first'] = { name = [[first]], desc = [[go to the first file in the argument list]], command = true },
  [':fold'] = { name = [[fold]], desc = [[create a fold]], command = true },
  [':foldclose'] = { name = [[foldclose]], desc = [[close folds]], command = true },
  [':folddoopen'] = { name = [[folddoopen]], desc = [[execute command on lines not in a closed fold]], command = true },
  [':folddoclosed'] = { name = [[folddoclosed]], desc = [[execute command on lines in a closed fold]], command = true },
  [':foldopen'] = { name = [[foldopen]], desc = [[open folds]], command = true },
  [':for'] = { name = [[for]], desc = [[for loop]], command = true },
  [':function'] = { name = [[function]], desc = [[define a user function]], command = true },
  [':global'] = { name = [[global]], desc = [[execute commands for matching lines]], command = true },
  [':goto'] = { name = [[goto]], desc = [[go to byte in the buffer]], command = true },
  [':grep'] = { name = [[grep]], desc = [[run 'grepprg' and jump to first match]], command = true },
  [':grepadd'] = { name = [[grepadd]], desc = [[like :grep, but append to current list]], command = true },
  [':gui'] = { name = [[gui]], desc = [[start the GUI]], command = true },
  [':gvim'] = { name = [[gvim]], desc = [[start the GUI]], command = true },
  [':help'] = { name = [[help]], desc = [[open a help window]], command = true },
  [':helpclose'] = { name = [[helpclose]], desc = [[close one help window]], command = true },
  [':helpgrep'] = { name = [[helpgrep]], desc = [[like ":grep" but searches help files]], command = true },
  [':helptags'] = { name = [[helptags]], desc = [[generate help tags for a directory]], command = true },
  [':highlight'] = { name = [[highlight]], desc = [[specify highlighting methods]], command = true },
  [':hide'] = { name = [[hide]], desc = [[hide current buffer for a command]], command = true },
  [':history'] = { name = [[history]], desc = [[print a history list]], command = true },
  [':horizontal'] = { name = [[horizontal]], desc = [[following window command work horizontally]], command = true },
  [':insert'] = { name = [[insert]], desc = [[insert text]], command = true },
  [':iabbrev'] = { name = [[iabbrev]], desc = [[like ":abbrev" but for Insert mode]], command = true },
  [':iabclear'] = { name = [[iabclear]], desc = [[like ":abclear" but for Insert mode]], command = true },
  [':if'] = { name = [[if]], desc = [[execute commands when condition met]], command = true },
  [':ijump'] = { name = [[ijump]], desc = [[jump to definition of identifier]], command = true },
  [':ilist'] = { name = [[ilist]], desc = [[list lines where identifier matches]], command = true },
  [':imap'] = { name = [[imap]], desc = [[like ":map" but for Insert mode]], command = true },
  [':imapclear'] = { name = [[imapclear]], desc = [[like ":mapclear" but for Insert mode]], command = true },
  [':imenu'] = { name = [[imenu]], desc = [[add menu for Insert mode]], command = true },
  [':inoremap'] = { name = [[inoremap]], desc = [[like ":noremap" but for Insert mode]], command = true },
  [':inoreabbrev'] = { name = [[inoreabbrev]], desc = [[like ":noreabbrev" but for Insert mode]], command = true },
  [':inoremenu'] = { name = [[inoremenu]], desc = [[like ":noremenu" but for Insert mode]], command = true },
  [':intro'] = { name = [[intro]], desc = [[print the introductory message]], command = true },
  [':isearch'] = { name = [[isearch]], desc = [[list one line where identifier matches]], command = true },
  [':isplit'] = { name = [[isplit]], desc = [[split window and jump to definition of identifier]], command = true },
  [':iunmap'] = { name = [[iunmap]], desc = [[like ":unmap" but for Insert mode]], command = true },
  [':iunabbrev'] = { name = [[iunabbrev]], desc = [[like ":unabbrev" but for Insert mode]], command = true },
  [':iunmenu'] = { name = [[iunmenu]], desc = [[remove menu for Insert mode]], command = true },
  [':join'] = { name = [[join]], desc = [[join lines]], command = true },
  [':jumps'] = { name = [[jumps]], desc = [[print the jump list]], command = true },
  [':k'] = { name = [[k]], desc = [[set a mark]], command = true },
  [':keepalt'] = { name = [[keepalt]], desc = [[following command keeps the alternate file]], command = true },
  [':keepmarks'] = { name = [[keepmarks]], desc = [[following command keeps marks where they are]], command = true },
  [':keepjumps'] = { name = [[keepjumps]], desc = [[following command keeps jumplist and marks]], command = true },
  [':keeppatterns'] = {
    name = [[keeppatterns]],
    desc = [[following command keeps search pattern history]],
    command = true,
  },
  [':lNext'] = { name = [[lNext]], desc = [[go to previous entry in location list]], command = true },
  [':lNfile'] = { name = [[lNfile]], desc = [[go to last entry in previous file]], command = true },
  [':list'] = { name = [[list]], desc = [[print lines]], command = true },
  [':labove'] = { name = [[labove]], desc = [[go to location above current line]], command = true },
  [':laddexpr'] = { name = [[laddexpr]], desc = [[add locations from expr]], command = true },
  [':laddbuffer'] = { name = [[laddbuffer]], desc = [[add locations from buffer]], command = true },
  [':laddfile'] = { name = [[laddfile]], desc = [[add locations to current location list]], command = true },
  [':lafter'] = { name = [[lafter]], desc = [[go to location after current cursor]], command = true },
  [':last'] = { name = [[last]], desc = [[go to the last file in the argument list]], command = true },
  [':language'] = { name = [[language]], desc = [[set the language (locale)]], command = true },
  [':later'] = { name = [[later]], desc = [[go to newer change, redo]], command = true },
  [':lbefore'] = { name = [[lbefore]], desc = [[go to location before current cursor]], command = true },
  [':lbelow'] = { name = [[lbelow]], desc = [[go to location below current line]], command = true },
  [':lbottom'] = { name = [[lbottom]], desc = [[scroll to the bottom of the location window]], command = true },
  [':lbuffer'] = { name = [[lbuffer]], desc = [[parse locations and jump to first location]], command = true },
  [':lcd'] = { name = [[lcd]], desc = [[change directory locally]], command = true },
  [':lchdir'] = { name = [[lchdir]], desc = [[change directory locally]], command = true },
  [':lclose'] = { name = [[lclose]], desc = [[close location window]], command = true },
  [':ldo'] = { name = [[ldo]], desc = [[execute command in valid location list entries]], command = true },
  [':lfdo'] = { name = [[lfdo]], desc = [[execute command in each file in location list]], command = true },
  [':left'] = { name = [[left]], desc = [[left align lines]], command = true },
  [':leftabove'] = { name = [[leftabove]], desc = [[make split window appear left or above]], command = true },
  [':let'] = { name = [[let]], desc = [[assign a value to a variable or option]], command = true },
  [':lexpr'] = { name = [[lexpr]], desc = [[read locations from expr and jump to first]], command = true },
  [':lfile'] = { name = [[lfile]], desc = [[read file with locations and jump to first]], command = true },
  [':lfirst'] = { name = [[lfirst]], desc = [[go to the specified location, default first one]], command = true },
  [':lgetbuffer'] = { name = [[lgetbuffer]], desc = [[get locations from buffer]], command = true },
  [':lgetexpr'] = { name = [[lgetexpr]], desc = [[get locations from expr]], command = true },
  [':lgetfile'] = { name = [[lgetfile]], desc = [[read file with locations]], command = true },
  [':lgrep'] = { name = [[lgrep]], desc = [[run 'grepprg' and jump to first match]], command = true },
  [':lgrepadd'] = { name = [[lgrepadd]], desc = [[like :grep, but append to current list]], command = true },
  [':lhelpgrep'] = { name = [[lhelpgrep]], desc = [[like ":helpgrep" but uses location list]], command = true },
  [':lhistory'] = { name = [[lhistory]], desc = [[list the location lists]], command = true },
  [':ll'] = { name = [[ll]], desc = [[go to specific location]], command = true },
  [':llast'] = { name = [[llast]], desc = [[go to the specified location, default last one]], command = true },
  [':llist'] = { name = [[llist]], desc = [[list all locations]], command = true },
  [':lmake'] = {
    name = [[lmake]],
    desc = [[execute external command 'makeprg' and parse error messages]],
    command = true,
  },
  [':lmap'] = { name = [[lmap]], desc = [[like ":map!" but includes Lang-Arg mode]], command = true },
  [':lmapclear'] = { name = [[lmapclear]], desc = [[like ":mapclear!" but includes Lang-Arg mode]], command = true },
  [':lnext'] = { name = [[lnext]], desc = [[go to next location]], command = true },
  [':lnewer'] = { name = [[lnewer]], desc = [[go to newer location list]], command = true },
  [':lnfile'] = { name = [[lnfile]], desc = [[go to first location in next file]], command = true },
  [':lnoremap'] = { name = [[lnoremap]], desc = [[like ":noremap!" but includes Lang-Arg mode]], command = true },
  [':loadkeymap'] = { name = [[loadkeymap]], desc = [[load the following keymaps until EOF]], command = true },
  [':loadview'] = { name = [[loadview]], desc = [[load view for current window from a file]], command = true },
  [':lockmarks'] = { name = [[lockmarks]], desc = [[following command keeps marks where they are]], command = true },
  [':lockvar'] = { name = [[lockvar]], desc = [[lock variables]], command = true },
  [':lolder'] = { name = [[lolder]], desc = [[go to older location list]], command = true },
  [':lopen'] = { name = [[lopen]], desc = [[open location window]], command = true },
  [':lprevious'] = { name = [[lprevious]], desc = [[go to previous location]], command = true },
  [':lpfile'] = { name = [[lpfile]], desc = [[go to last location in previous file]], command = true },
  [':lrewind'] = { name = [[lrewind]], desc = [[go to the specified location, default first one]], command = true },
  [':ls'] = { name = [[ls]], desc = [[list all buffers]], command = true },
  [':ltag'] = { name = [[ltag]], desc = [[jump to tag and add matching tags to the location list]], command = true },
  [':lunmap'] = { name = [[lunmap]], desc = [[like ":unmap!" but includes Lang-Arg mode]], command = true },
  [':lua'] = { name = [[lua]], desc = [[execute |Lua| command]], command = true },
  [':luado'] = { name = [[luado]], desc = [[execute Lua command for each line]], command = true },
  [':luafile'] = { name = [[luafile]], desc = [[execute |Lua| script file]], command = true },
  [':lvimgrep'] = { name = [[lvimgrep]], desc = [[search for pattern in files]], command = true },
  [':lvimgrepadd'] = { name = [[lvimgrepadd]], desc = [[like :vimgrep, but append to current list]], command = true },
  [':lwindow'] = { name = [[lwindow]], desc = [[open or close location window]], command = true },
  [':move'] = { name = [[move]], desc = [[move lines]], command = true },
  [':mark'] = { name = [[mark]], desc = [[set a mark]], command = true },
  [':make'] = { name = [[make]], desc = [[execute external command 'makeprg' and parse error messages]], command = true },
  [':map'] = { name = [[map]], desc = [[show or enter a mapping]], command = true },
  [':mapclear'] = { name = [[mapclear]], desc = [[clear all mappings for Normal and Visual mode]], command = true },
  [':marks'] = { name = [[marks]], desc = [[list all marks]], command = true },
  [':match'] = { name = [[match]], desc = [[define a match to highlight]], command = true },
  [':menu'] = { name = [[menu]], desc = [[enter a new menu item]], command = true },
  [':menutranslate'] = { name = [[menutranslate]], desc = [[add a menu translation item]], command = true },
  [':messages'] = { name = [[messages]], desc = [[view previously displayed messages]], command = true },
  [':mkexrc'] = { name = [[mkexrc]], desc = [[write current mappings and settings to a file]], command = true },
  [':mksession'] = { name = [[mksession]], desc = [[write session info to a file]], command = true },
  [':mkspell'] = { name = [[mkspell]], desc = [[produce .spl spell file]], command = true },
  [':mkvimrc'] = { name = [[mkvimrc]], desc = [[write current mappings and settings to a file]], command = true },
  [':mkview'] = { name = [[mkview]], desc = [[write view of current window to a file]], command = true },
  [':mode'] = { name = [[mode]], desc = [[show or change the screen mode]], command = true },
  [':next'] = { name = [[next]], desc = [[go to next file in the argument list]], command = true },
  [':new'] = { name = [[new]], desc = [[create a new empty window]], command = true },
  [':nmap'] = { name = [[nmap]], desc = [[like ":map" but for Normal mode]], command = true },
  [':nmapclear'] = { name = [[nmapclear]], desc = [[clear all mappings for Normal mode]], command = true },
  [':nmenu'] = { name = [[nmenu]], desc = [[add menu for Normal mode]], command = true },
  [':nnoremap'] = { name = [[nnoremap]], desc = [[like ":noremap" but for Normal mode]], command = true },
  [':nnoremenu'] = { name = [[nnoremenu]], desc = [[like ":noremenu" but for Normal mode]], command = true },
  [':noautocmd'] = { name = [[noautocmd]], desc = [[following commands don't trigger autocommands]], command = true },
  [':noremap'] = { name = [[noremap]], desc = [[enter a mapping that will not be remapped]], command = true },
  [':nohlsearch'] = { name = [[nohlsearch]], desc = [[suspend 'hlsearch' highlighting]], command = true },
  [':noreabbrev'] = { name = [[noreabbrev]], desc = [[enter an abbreviation that will not be remapped]], command = true },
  [':noremenu'] = { name = [[noremenu]], desc = [[enter a menu that will not be remapped]], command = true },
  [':normal'] = { name = [[normal]], desc = [[execute Normal mode commands]], command = true },
  [':noswapfile'] = { name = [[noswapfile]], desc = [[following commands don't create a swap file]], command = true },
  [':number'] = { name = [[number]], desc = [[print lines with line number]], command = true },
  [':nunmap'] = { name = [[nunmap]], desc = [[like ":unmap" but for Normal mode]], command = true },
  [':nunmenu'] = { name = [[nunmenu]], desc = [[remove menu for Normal mode]], command = true },
  [':oldfiles'] = { name = [[oldfiles]], desc = [[list files that have marks in the |shada| file]], command = true },
  [':omap'] = { name = [[omap]], desc = [[like ":map" but for Operator-pending mode]], command = true },
  [':omapclear'] = { name = [[omapclear]], desc = [[remove all mappings for Operator-pending mode]], command = true },
  [':omenu'] = { name = [[omenu]], desc = [[add menu for Operator-pending mode]], command = true },
  [':only'] = { name = [[only]], desc = [[close all windows except the current one]], command = true },
  [':onoremap'] = { name = [[onoremap]], desc = [[like ":noremap" but for Operator-pending mode]], command = true },
  [':onoremenu'] = { name = [[onoremenu]], desc = [[like ":noremenu" but for Operator-pending mode]], command = true },
  [':options'] = { name = [[options]], desc = [[open the options-window]], command = true },
  [':ounmap'] = { name = [[ounmap]], desc = [[like ":unmap" but for Operator-pending mode]], command = true },
  [':ounmenu'] = { name = [[ounmenu]], desc = [[remove menu for Operator-pending mode]], command = true },
  [':ownsyntax'] = { name = [[ownsyntax]], desc = [[set new local syntax highlight for this window]], command = true },
  [':packadd'] = { name = [[packadd]], desc = [[add a plugin from 'packpath']], command = true },
  [':packloadall'] = { name = [[packloadall]], desc = [[load all packages under 'packpath']], command = true },
  [':pclose'] = { name = [[pclose]], desc = [[close preview window]], command = true },
  [':pedit'] = { name = [[pedit]], desc = [[edit file in the preview window]], command = true },
  [':perl'] = { name = [[perl]], desc = [[execute perl command]], command = true },
  [':perldo'] = { name = [[perldo]], desc = [[execute perl command for each line]], command = true },
  [':perlfile'] = { name = [[perlfile]], desc = [[execute perl script file]], command = true },
  [':print'] = { name = [[print]], desc = [[print lines]], command = true },
  [':profdel'] = { name = [[profdel]], desc = [[stop profiling a function or script]], command = true },
  [':profile'] = { name = [[profile]], desc = [[profiling functions and scripts]], command = true },
  [':pop'] = { name = [[pop]], desc = [[jump to older entry in tag stack]], command = true },
  [':popup'] = { name = [[popup]], desc = [[popup a menu by name]], command = true },
  [':ppop'] = { name = [[ppop]], desc = [[":pop" in preview window]], command = true },
  [':preserve'] = { name = [[preserve]], desc = [[write all text to swap file]], command = true },
  [':previous'] = { name = [[previous]], desc = [[go to previous file in argument list]], command = true },
  [':psearch'] = { name = [[psearch]], desc = [[like ":ijump" but shows match in preview window]], command = true },
  [':ptag'] = { name = [[ptag]], desc = [[show tag in preview window]], command = true },
  [':ptNext|	:ptN[ext]	'] = { name = [[ptNext|	:ptN[ext]	]], desc = [[in preview window]], command = true },
  [':ptfirst|	:ptf[irst]	'] = { name = [[ptfirst|	:ptf[irst]	]], desc = [[in preview window]], command = true },
  [':ptjump|	:ptj[ump]	'] = { name = [[ptjump|	:ptj[ump]	]], desc = [[and show tag in preview window]], command = true },
  [':ptlast|	:ptl[ast]	'] = { name = [[ptlast|	:ptl[ast]	]], desc = [[in preview window]], command = true },
  [':ptnext|	:ptn[ext]	'] = { name = [[ptnext|	:ptn[ext]	]], desc = [[in preview window]], command = true },
  [':ptprevious|	:ptp[revious]	'] = {
    name = [[ptprevious|	:ptp[revious]	]],
    desc = [[in preview window]],
    command = true,
  },
  [':ptrewind|	:ptr[ewind]	'] = { name = [[ptrewind|	:ptr[ewind]	]], desc = [[in preview window]], command = true },
  [':ptselect|	:pts[elect]	'] = {
    name = [[ptselect|	:pts[elect]	]],
    desc = [[and show tag in preview window]],
    command = true,
  },
  [':put'] = { name = [[put]], desc = [[insert contents of register in the text]], command = true },
  [':pwd'] = { name = [[pwd]], desc = [[print current directory]], command = true },
  [':py3'] = { name = [[py3]], desc = [[execute Python 3 command]], command = true },
  [':python3'] = { name = [[python3]], desc = [[same as :py3]], command = true },
  [':py3do'] = { name = [[py3do]], desc = [[execute Python 3 command for each line]], command = true },
  [':py3file'] = { name = [[py3file]], desc = [[execute Python 3 script file]], command = true },
  [':python'] = { name = [[python]], desc = [[execute Python command]], command = true },
  [':pydo'] = { name = [[pydo]], desc = [[execute Python command for each line]], command = true },
  [':pyfile'] = { name = [[pyfile]], desc = [[execute Python script file]], command = true },
  [':pyx'] = { name = [[pyx]], desc = [[execute |python_x| command]], command = true },
  [':pythonx'] = { name = [[pythonx]], desc = [[same as :pyx]], command = true },
  [':pyxdo'] = { name = [[pyxdo]], desc = [[execute |python_x| command for each line]], command = true },
  [':pyxfile'] = { name = [[pyxfile]], desc = [[execute |python_x| script file]], command = true },
  [':quit'] = { name = [[quit]], desc = [[quit current window (when one window quit Vim)]], command = true },
  [':quitall'] = { name = [[quitall]], desc = [[quit Vim]], command = true },
  [':qall'] = { name = [[qall]], desc = [[quit Vim]], command = true },
  [':read'] = { name = [[read]], desc = [[read file into the text]], command = true },
  [':recover'] = { name = [[recover]], desc = [[recover a file from a swap file]], command = true },
  [':redo'] = { name = [[redo]], desc = [[redo one undone change]], command = true },
  [':redir'] = { name = [[redir]], desc = [[redirect messages to a file or register]], command = true },
  [':redraw'] = { name = [[redraw]], desc = [[force a redraw of the display]], command = true },
  [':redrawstatus'] = {
    name = [[redrawstatus]],
    desc = [[force a redraw of the status line(s) and window bar(s)]],
    command = true,
  },
  [':redrawtabline'] = { name = [[redrawtabline]], desc = [[force a redraw of the tabline]], command = true },
  [':registers'] = { name = [[registers]], desc = [[display the contents of registers]], command = true },
  [':resize'] = { name = [[resize]], desc = [[change current window height]], command = true },
  [':retab'] = { name = [[retab]], desc = [[change tab size]], command = true },
  [':return'] = { name = [[return]], desc = [[return from a user function]], command = true },
  [':rewind'] = { name = [[rewind]], desc = [[go to the first file in the argument list]], command = true },
  [':right'] = { name = [[right]], desc = [[right align text]], command = true },
  [':rightbelow'] = { name = [[rightbelow]], desc = [[make split window appear right or below]], command = true },
  [':rshada'] = { name = [[rshada]], desc = [[read from |shada| file]], command = true },
  [':ruby'] = { name = [[ruby]], desc = [[execute Ruby command]], command = true },
  [':rubydo'] = { name = [[rubydo]], desc = [[execute Ruby command for each line]], command = true },
  [':rubyfile'] = { name = [[rubyfile]], desc = [[execute Ruby script file]], command = true },
  [':rundo'] = { name = [[rundo]], desc = [[read undo information from a file]], command = true },
  [':runtime'] = { name = [[runtime]], desc = [[source vim scripts in 'runtimepath']], command = true },
  [':substitute'] = { name = [[substitute]], desc = [[find and replace text]], command = true },
  [':sNext'] = { name = [[sNext]], desc = [[split window and go to previous file in argument list]], command = true },
  [':sandbox'] = { name = [[sandbox]], desc = [[execute a command in the sandbox]], command = true },
  [':sargument'] = {
    name = [[sargument]],
    desc = [[split window and go to specific file in argument list]],
    command = true,
  },
  [':sall'] = { name = [[sall]], desc = [[open a window for each file in argument list]], command = true },
  [':saveas'] = { name = [[saveas]], desc = [[save file under another name.]], command = true },
  [':sbuffer'] = {
    name = [[sbuffer]],
    desc = [[split window and go to specific file in the buffer list]],
    command = true,
  },
  [':sbNext'] = { name = [[sbNext]], desc = [[split window and go to previous file in the buffer list]], command = true },
  [':sball'] = { name = [[sball]], desc = [[open a window for each file in the buffer list]], command = true },
  [':sbfirst'] = { name = [[sbfirst]], desc = [[split window and go to first file in the buffer list]], command = true },
  [':sblast'] = { name = [[sblast]], desc = [[split window and go to last file in buffer list]], command = true },
  [':sbmodified'] = {
    name = [[sbmodified]],
    desc = [[split window and go to modified file in the buffer list]],
    command = true,
  },
  [':sbnext'] = { name = [[sbnext]], desc = [[split window and go to next file in the buffer list]], command = true },
  [':sbprevious'] = {
    name = [[sbprevious]],
    desc = [[split window and go to previous file in the buffer list]],
    command = true,
  },
  [':sbrewind'] = { name = [[sbrewind]], desc = [[split window and go to first file in the buffer list]], command = true },
  [':scriptnames'] = { name = [[scriptnames]], desc = [[list names of all sourced Vim scripts]], command = true },
  [':scriptencoding'] = { name = [[scriptencoding]], desc = [[encoding used in sourced Vim script]], command = true },
  [':set'] = { name = [[set]], desc = [[show or set options]], command = true },
  [':setfiletype'] = { name = [[setfiletype]], desc = [[set 'filetype', unless it was set already]], command = true },
  [':setglobal'] = { name = [[setglobal]], desc = [[show global values of options]], command = true },
  [':setlocal'] = { name = [[setlocal]], desc = [[show or set options locally]], command = true },
  [':sfind'] = { name = [[sfind]], desc = [[split current window and edit file in 'path']], command = true },
  [':sfirst'] = { name = [[sfirst]], desc = [[split window and go to first file in the argument list]], command = true },
  [':sign'] = { name = [[sign]], desc = [[manipulate signs]], command = true },
  [':silent'] = { name = [[silent]], desc = [[run a command silently]], command = true },
  [':sleep'] = { name = [[sleep]], desc = [[do nothing for a few seconds]], command = true },
  [':slast'] = { name = [[slast]], desc = [[split window and go to last file in the argument list]], command = true },
  [':smagic'] = { name = [[smagic]], desc = [[:substitute with 'magic']], command = true },
  [':smap'] = { name = [[smap]], desc = [[like ":map" but for Select mode]], command = true },
  [':smapclear'] = { name = [[smapclear]], desc = [[remove all mappings for Select mode]], command = true },
  [':smenu'] = { name = [[smenu]], desc = [[add menu for Select mode]], command = true },
  [':snext'] = { name = [[snext]], desc = [[split window and go to next file in the argument list]], command = true },
  [':snomagic'] = { name = [[snomagic]], desc = [[:substitute with 'nomagic']], command = true },
  [':snoremap'] = { name = [[snoremap]], desc = [[like ":noremap" but for Select mode]], command = true },
  [':snoremenu'] = { name = [[snoremenu]], desc = [[like ":noremenu" but for Select mode]], command = true },
  [':sort'] = { name = [[sort]], desc = [[sort lines]], command = true },
  [':source'] = { name = [[source]], desc = [[read Vim or Ex commands from a file]], command = true },
  [':spelldump'] = { name = [[spelldump]], desc = [[split window and fill with all correct words]], command = true },
  [':spellgood'] = { name = [[spellgood]], desc = [[add good word for spelling]], command = true },
  [':spellinfo'] = { name = [[spellinfo]], desc = [[show info about loaded spell files]], command = true },
  [':spellrare'] = { name = [[spellrare]], desc = [[add rare word for spelling]], command = true },
  [':spellrepall'] = { name = [[spellrepall]], desc = [[replace all bad words like last |z=|]], command = true },
  [':spellundo'] = { name = [[spellundo]], desc = [[remove good or bad word]], command = true },
  [':spellwrong'] = { name = [[spellwrong]], desc = [[add spelling mistake]], command = true },
  [':split'] = { name = [[split]], desc = [[split current window]], command = true },
  [':sprevious'] = {
    name = [[sprevious]],
    desc = [[split window and go to previous file in the argument list]],
    command = true,
  },
  [':srewind'] = { name = [[srewind]], desc = [[split window and go to first file in the argument list]], command = true },
  [':stop'] = { name = [[stop]], desc = [[suspend the editor or escape to a shell]], command = true },
  [':stag'] = { name = [[stag]], desc = [[split window and jump to a tag]], command = true },
  [':startinsert'] = { name = [[startinsert]], desc = [[start Insert mode]], command = true },
  [':startgreplace'] = { name = [[startgreplace]], desc = [[start Virtual Replace mode]], command = true },
  [':startreplace'] = { name = [[startreplace]], desc = [[start Replace mode]], command = true },
  [':stopinsert'] = { name = [[stopinsert]], desc = [[stop Insert mode]], command = true },
  [':stjump'] = { name = [[stjump]], desc = [[do ":tjump" and split window]], command = true },
  [':stselect'] = { name = [[stselect]], desc = [[do ":tselect" and split window]], command = true },
  [':sunhide'] = { name = [[sunhide]], desc = [[same as ":unhide"]], command = true },
  [':sunmap'] = { name = [[sunmap]], desc = [[like ":unmap" but for Select mode]], command = true },
  [':sunmenu'] = { name = [[sunmenu]], desc = [[remove menu for Select mode]], command = true },
  [':suspend'] = { name = [[suspend]], desc = [[same as ":stop"]], command = true },
  [':sview'] = { name = [[sview]], desc = [[split window and edit file read-only]], command = true },
  [':swapname'] = { name = [[swapname]], desc = [[show the name of the current swap file]], command = true },
  [':syntax'] = { name = [[syntax]], desc = [[syntax highlighting]], command = true },
  [':syntime'] = { name = [[syntime]], desc = [[measure syntax highlighting speed]], command = true },
  [':syncbind'] = { name = [[syncbind]], desc = [[sync scroll binding]], command = true },
  [':t'] = { name = [[t]], desc = [[same as ":copy"]], command = true },
  [':tNext'] = { name = [[tNext]], desc = [[jump to previous matching tag]], command = true },
  [':tabNext'] = { name = [[tabNext]], desc = [[go to previous tab page]], command = true },
  [':tabclose'] = { name = [[tabclose]], desc = [[close current tab page]], command = true },
  [':tabdo'] = { name = [[tabdo]], desc = [[execute command in each tab page]], command = true },
  [':tabedit'] = { name = [[tabedit]], desc = [[edit a file in a new tab page]], command = true },
  [':tabfind'] = { name = [[tabfind]], desc = [[find file in 'path', edit it in a new tab page]], command = true },
  [':tabfirst'] = { name = [[tabfirst]], desc = [[go to first tab page]], command = true },
  [':tablast'] = { name = [[tablast]], desc = [[go to last tab page]], command = true },
  [':tabmove'] = { name = [[tabmove]], desc = [[move tab page to other position]], command = true },
  [':tabnew'] = { name = [[tabnew]], desc = [[edit a file in a new tab page]], command = true },
  [':tabnext'] = { name = [[tabnext]], desc = [[go to next tab page]], command = true },
  [':tabonly'] = { name = [[tabonly]], desc = [[close all tab pages except the current one]], command = true },
  [':tabprevious'] = { name = [[tabprevious]], desc = [[go to previous tab page]], command = true },
  [':tabrewind'] = { name = [[tabrewind]], desc = [[go to first tab page]], command = true },
  [':tabs'] = { name = [[tabs]], desc = [[list the tab pages and what they contain]], command = true },
  [':tab'] = { name = [[tab]], desc = [[create new tab when opening new window]], command = true },
  [':tag'] = { name = [[tag]], desc = [[jump to tag]], command = true },
  [':tags'] = { name = [[tags]], desc = [[show the contents of the tag stack]], command = true },
  [':tcd'] = { name = [[tcd]], desc = [[change directory for tab page]], command = true },
  [':tchdir'] = { name = [[tchdir]], desc = [[change directory for tab page]], command = true },
  [':terminal'] = { name = [[terminal]], desc = [[open a terminal buffer]], command = true },
  [':tfirst'] = { name = [[tfirst]], desc = [[jump to first matching tag]], command = true },
  [':throw'] = { name = [[throw]], desc = [[throw an exception]], command = true },
  [':tjump'] = {
    name = [[tjump]],
    desc = [[like ":tselect", but jump directly when there is only one match]],
    command = true,
  },
  [':tlast'] = { name = [[tlast]], desc = [[jump to last matching tag]], command = true },
  [':tlmenu'] = { name = [[tlmenu]], desc = [[add menu for |Terminal-mode|]], command = true },
  [':tlnoremenu'] = { name = [[tlnoremenu]], desc = [[like ":noremenu" but for |Terminal-mode|]], command = true },
  [':tlunmenu'] = { name = [[tlunmenu]], desc = [[remove menu for |Terminal-mode|]], command = true },
  [':tmapclear'] = { name = [[tmapclear]], desc = [[remove all mappings for |Terminal-mode|]], command = true },
  [':tmap'] = { name = [[tmap]], desc = [[like ":map" but for |Terminal-mode|]], command = true },
  [':tmenu'] = { name = [[tmenu]], desc = [[define menu tooltip]], command = true },
  [':tnext'] = { name = [[tnext]], desc = [[jump to next matching tag]], command = true },
  [':tnoremap'] = { name = [[tnoremap]], desc = [[like ":noremap" but for |Terminal-mode|]], command = true },
  [':topleft'] = { name = [[topleft]], desc = [[make split window appear at top or far left]], command = true },
  [':tprevious'] = { name = [[tprevious]], desc = [[jump to previous matching tag]], command = true },
  [':trewind'] = { name = [[trewind]], desc = [[jump to first matching tag]], command = true },
  [':trust'] = { name = [[trust]], desc = [[add or remove file from trust database]], command = true },
  [':try'] = { name = [[try]], desc = [[execute commands, abort on error or exception]], command = true },
  [':tselect'] = { name = [[tselect]], desc = [[list matching tags and select one]], command = true },
  [':tunmap'] = { name = [[tunmap]], desc = [[like ":unmap" but for |Terminal-mode|]], command = true },
  [':tunmenu'] = { name = [[tunmenu]], desc = [[remove menu tooltip]], command = true },
  [':undo'] = { name = [[undo]], desc = [[undo last change(s)]], command = true },
  [':undojoin'] = { name = [[undojoin]], desc = [[join next change with previous undo block]], command = true },
  [':undolist'] = { name = [[undolist]], desc = [[list leafs of the undo tree]], command = true },
  [':unabbreviate'] = { name = [[unabbreviate]], desc = [[remove abbreviation]], command = true },
  [':unhide'] = { name = [[unhide]], desc = [[open a window for each loaded file in the buffer list]], command = true },
  [':unlet'] = { name = [[unlet]], desc = [[delete variable]], command = true },
  [':unlockvar'] = { name = [[unlockvar]], desc = [[unlock variables]], command = true },
  [':unmap'] = { name = [[unmap]], desc = [[remove mapping]], command = true },
  [':unmenu'] = { name = [[unmenu]], desc = [[remove menu]], command = true },
  [':unsilent'] = { name = [[unsilent]], desc = [[run a command not silently]], command = true },
  [':update'] = { name = [[update]], desc = [[write buffer if modified]], command = true },
  [':vglobal'] = { name = [[vglobal]], desc = [[execute commands for not matching lines]], command = true },
  [':version'] = { name = [[version]], desc = [[print version number and other info]], command = true },
  [':verbose'] = { name = [[verbose]], desc = [[execute command with 'verbose' set]], command = true },
  [':vertical'] = { name = [[vertical]], desc = [[make following command split vertically]], command = true },
  [':vimgrep'] = { name = [[vimgrep]], desc = [[search for pattern in files]], command = true },
  [':vimgrepadd'] = { name = [[vimgrepadd]], desc = [[like :vimgrep, but append to current list]], command = true },
  [':visual'] = { name = [[visual]], desc = [[same as ":edit", but turns off "Ex" mode]], command = true },
  [':viusage'] = { name = [[viusage]], desc = [[overview of Normal mode commands]], command = true },
  [':view'] = { name = [[view]], desc = [[edit a file read-only]], command = true },
  [':vmap'] = { name = [[vmap]], desc = [[like ":map" but for Visual+Select mode]], command = true },
  [':vmapclear'] = { name = [[vmapclear]], desc = [[remove all mappings for Visual+Select mode]], command = true },
  [':vmenu'] = { name = [[vmenu]], desc = [[add menu for Visual+Select mode]], command = true },
  [':vnew'] = { name = [[vnew]], desc = [[create a new empty window, vertically split]], command = true },
  [':vnoremap'] = { name = [[vnoremap]], desc = [[like ":noremap" but for Visual+Select mode]], command = true },
  [':vnoremenu'] = { name = [[vnoremenu]], desc = [[like ":noremenu" but for Visual+Select mode]], command = true },
  [':vsplit'] = { name = [[vsplit]], desc = [[split current window vertically]], command = true },
  [':vunmap'] = { name = [[vunmap]], desc = [[like ":unmap" but for Visual+Select mode]], command = true },
  [':vunmenu'] = { name = [[vunmenu]], desc = [[remove menu for Visual+Select mode]], command = true },
  [':windo'] = { name = [[windo]], desc = [[execute command in each window]], command = true },
  [':write'] = { name = [[write]], desc = [[write to a file]], command = true },
  [':wNext'] = { name = [[wNext]], desc = [[write to a file and go to previous file in argument list]], command = true },
  [':wall'] = { name = [[wall]], desc = [[write all (changed) buffers]], command = true },
  [':while'] = { name = [[while]], desc = [[execute loop for as long as condition met]], command = true },
  [':winsize'] = { name = [[winsize]], desc = [[get or set window size (obsolete)]], command = true },
  [':wincmd'] = { name = [[wincmd]], desc = [[execute a Window (CTRL-W) command]], command = true },
  [':winpos'] = { name = [[winpos]], desc = [[get or set window position]], command = true },
  [':wnext'] = { name = [[wnext]], desc = [[write to a file and go to next file in argument list]], command = true },
  [':wprevious'] = {
    name = [[wprevious]],
    desc = [[write to a file and go to previous file in argument list]],
    command = true,
  },
  [':wq'] = { name = [[wq]], desc = [[write to a file and quit window or Vim]], command = true },
  [':wqall'] = { name = [[wqall]], desc = [[write all changed buffers and quit Vim]], command = true },
  [':wshada'] = { name = [[wshada]], desc = [[write to ShaDa file]], command = true },
  [':wundo'] = { name = [[wundo]], desc = [[write undo information to a file]], command = true },
  [':xit'] = { name = [[xit]], desc = [[write if buffer changed and close window]], command = true },
  [':xall'] = { name = [[xall]], desc = [[same as ":wqall"]], command = true },
  [':xmapclear'] = { name = [[xmapclear]], desc = [[remove all mappings for Visual mode]], command = true },
  [':xmap'] = { name = [[xmap]], desc = [[like ":map" but for Visual mode]], command = true },
  [':xmenu'] = { name = [[xmenu]], desc = [[add menu for Visual mode]], command = true },
  [':xnoremap'] = { name = [[xnoremap]], desc = [[like ":noremap" but for Visual mode]], command = true },
  [':xnoremenu'] = { name = [[xnoremenu]], desc = [[like ":noremenu" but for Visual mode]], command = true },
  [':xunmap'] = { name = [[xunmap]], desc = [[like ":unmap" but for Visual mode]], command = true },
  [':xunmenu'] = { name = [[xunmenu]], desc = [[remove menu for Visual mode]], command = true },
  [':yank'] = { name = [[yank]], desc = [[yank lines into a register]], command = true },
  [':z'] = { name = [[z]], desc = [[print some lines]], command = true },
  [':~'] = { name = [[~]], desc = [[repeat last ":substitute"]], command = true },
}

---@param opts CommandPalConfig
---@return palette.MappedAction
function M:__map_builtins(opts)
  local builtin = {}

  for k, v in pairs(self.builtin) do
    if not v.bang and opts.builtin.bang == false then
      builtin[k] = {
        name = v.name,
        group = v.group or 'Vim',
        desc = v.desc,
        command = (function()
          if type(v.command) == 'boolean' and v.command then
            return set_cmd(k .. ' ')
          else
            return k
          end
        end)(),
        cmd_str = k,
        handler = default_handler,
        ordinal = get_ordinal(v, opts),
      }
    end
  end

  return builtin
end

function M.get_items(opts) return M:__map_builtins(opts) end

return M
